### ISSUE TITLE
Disk addition denied by terraform

### ISSUE THREAD

**Issue by daya8143** [hashicorp/terraform-provider-vsphere#2140] opened 2024-03-01 11:45 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

~> 1.1.2

### Terraform Provider

~> 1.1.2

### VMware vSphere

~> 2.1.1

### Description

Error: disk.0: virtual disk "disk0": cannot change the value of "thin_provisioned" - (old: true newValue: false)

### Affected Resources or Data Sources

resource "vsphere_virtual_machine" 

### Terraform Configuration

module "madley-SOTA" {
  source = "git::https://**"
  site = "prod-x-app"
  hosts =   { ** }
  component_name = "**"
  additional_disk_size = [**]
  netmask    = [*]
  gateway  = "*"
  vlan     = ["*"]
  use_cluster_datastore = true
}

### Debug Output

User
Error: disk.0: virtual disk "disk0": cannot change the value of "thin_provisioned" - (old: true newValue: false)

  with module.*-*.module.*-server.vsphere_virtual_machine.vm["*"],
  on .terraform/modules/*-*.*-server/main.tf line 64, in resource "vsphere_virtual_machine" "vm":
  64: resource "vsphere_virtual_machine" "vm" {

### Expected Behavior

Disk should be added

### Actual Behavior

Denied

### Steps to Reproduce

Added Disk to the tf

### References

https://github.com/hashicorp/terraform-provider-vsphere/issues/754#issue-437935303

**Comment by spacegospod** [comment] 2024-04-24 14:44
Duplicate of #2116

**Closed by spacegospod** 2024-04-24 14:44 UTC
Labels: bug, needs-triage
