### ISSUE TITLE
Plugin did not respond : Stack trace from the terraform-provider-vsphere_v2.8.2_x5.exe plugin

### ISSUE THREAD

**Issue by Josegc1989** [hashicorp/terraform-provider-vsphere#2238] opened 2024-07-08 08:38 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

2.31

### Terraform Provider

2.8.2

### VMware vSphere

7

### Description

When I run terraform plan o apply the terminal give me the next error:

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│   with vsphere_virtual_machine.vm,
│   on VM desde Plantilla.tf line 36, in resource "vsphere_virtual_machine" "vm":
│   36: resource "vsphere_virtual_machine" "vm" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vsphere_v2.8.2_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1244bda]

### Affected Resources or Data Sources

vm

### Terraform Configuration

x

### Debug Output

Planning failed. Terraform encountered an error while generating this plan.

### Expected Behavior

 x

### Actual Behavior

 x

### Steps to Reproduce

 x

**Comment by Josegc1989** [comment] 2024-07-08 08:47
I resolved the problem deleting the archive "terraform.lock.hcl"

**Comment by spacegospod** [comment] 2024-07-08 10:28
Hey @Josegc1989 glad to see you have a workaround.
Can you reproduce the problem again with debug logging enabled or at least share your configuration?
There's not enough data to track down the cause of the panic

**Comment by spacegospod** [comment] 2024-07-26 12:24
Reporter has indicated that they have resolved the problem, closing the PR

**Closed by spacegospod** 2024-07-26 12:24 UTC
Labels: bug, crash, waiting-response
