### ISSUE TITLE
Add support for assigning disks to multiple datastore clusters

### ISSUE THREAD

**Issue by ALK4** [hashicorp/terraform-provider-vsphere#1656] opened 2022-04-26 16:13 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently, the vsphere provider will only use a single datastore cluster set on the VM level.  Please allow support for assigning the VM to one datastore cluster, and the disks to separate clusters.

### Use Case(s)

VMs may run on multiple datastore clusters.  This configuration works with the Vsphere GUI

**Comment by tenthirtyam** [comment] 2022-04-26 16:18
Hi @ALK4 - I've updated your original issue content to use the **full** enhancement request template.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-04-26 16:20
Duplicate of #1601.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-04-26 16:22
Closing with a preference for the pre-existing issue #1601.

Vote on #1601 by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Closed** 2022-06-03 16:08 UTC
Labels: duplicate, enhancement, acknowledged, area/vm, area/storage
