### ISSUE TITLE
Context deadline exceeded on VMs with large disks

### ISSUE THREAD

**Issue by illmatik0ne** [hashicorp/terraform-provider-vsphere#1662] opened 2022-05-20 01:58 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.9

### Terraform Provider

v2.1.1

### VMware vSphere

v7.0.2

### Description

When attempting to configure a virtual machine with large eager zeroed disks terraform, terraform times out after 5 minutes with the following error:

Error: error reconfiguring virtual machine: error reconfiguring virtual machine: Post "https://vcenter.fqdn/sdk": context deadline exceeded

This is happening despite having the api_timeout set above the default for the provider as referenced in: 
[#1405](https://github.com/hashicorp/terraform-provider-vsphere/pull/1405)

### Affected Resources

resource "vsphere_virtual_machine"

### Terraform Configuration

```
terraform {
  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = "2.1.1"
    }
  }
}

provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = "var.vcenter_server"
  allow_unverified_ssl = false
  api_timeout          = 20
}
```

### Expected Behavior

The api_timeout provider parameter should override the default 5 minute timeout.

### Actual Behavior

The reconfigure virtual machine operation times out after 5 minutes and the terraform apply fails.

### Steps to Reproduce

YMMV, you may need a larger disk if your clone job completes faster than 5 minutes.

terraform apply with the TF config for a server with a large (400GB) thick-provisioned eager-zeroed secondary disk.
Wait 5 minutes.
Observe vCenter with a task in the queue to delete the virtual machine you're deploying.
Watch TF fail after the clone job completes with
Error: error reconfiguring virtual machine: error reconfiguring virtual machine: Post "https://vcenter.fqdn/sdk": context deadline exceeded

### Environment Details

Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.1.1

### References

#1134 
#1405

**Comment by tenthirtyam** [comment] 2022-06-02 14:05
Appears to be a duplicate of GH-1646.

This issue should be addressed in GH-1645 (Pull Request) for GH-1646 (Issue) which seeks to ensure that the `api_timeout` is applied to each virtual machine reconfiguration tasks.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Closed** 2022-07-26 02:19 UTC
Labels: duplicate, needs-triage, acknowledged, area/vm
