### ISSUE TITLE
Documentation: vsphere_distributed_port_group - import example is wrong

### ISSUE THREAD

**Issue by FinweVI** [hashicorp/terraform-provider-vsphere#1567] opened 2022-02-01 12:15 UTC
### Terraform Version

1.1.4

### vSphere Provider Version

2.0.2

### vSphere Version

6.7.0

### Affected Resource(s)

- `vsphere_distributed_port_group`

### Expected Behavior

Importing a DPG should work as stated in the [documentation](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/distributed_port_group#importing):
```
terraform import vsphere_distributed_port_group.pg dvportgroup-67
```

### Actual Behavior

When importing a DPG, terraform ask to specify a datacenter
```
terraform import module.MyDPG.vsphere_distributed_port_group.pg dvportgroup-xxx
module.MyDPG.vsphere_distributed_port_group.pg: Importing from ID "dvportgroup-xxx"...
╷
│ Error: error locating portgroup: please specify a datacenter
│
│
╵
```

I had to find the proper path of my DPG with `govc ls` and then import it this way:
```
terraform import module.MyDPG.vsphere_distributed_port_group.pg /DC/network/MyDPGFullName
```

### Steps to Reproduce

1. Create a DPG outside of Terraform
2. Try to import it

### Important Factoids

All my DPGs are linked to a DVS
I'm using a small homemade module for managing my DPGs, mainly just setting the variables for the Datacenter/DVS/Cluster inside.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by tenthirtyam** [comment] 2022-02-01 12:21
Duplicate of #1461

**Closed** 2022-02-01 22:09 UTC
Labels: duplicate, documentation
