### ISSUE TITLE
Add support for PV SCSI increased device count

### ISSUE THREAD

**Issue by elessyl** [hashicorp/terraform-provider-vsphere#1757] opened 2022-09-20 10:46 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

From ESXi 6.7 and above the PV SCSI SCSI adapter allows using 64 disks per controller.
The current Terraform provider still calculating with the old limits thus making this ability unusable via the terraform provider.

[VMware Configuration Limits](https://configmax.esp.vmware.com/guest?vmwareproduct=vSphere&release=vSphere%206.7&categories=1-0)

### Use Case(s)

When creating a VM with a disks more than 60 we need to use PV SCSI. This is really common with RAC setups.

**Comment by tenthirtyam** [comment] 2022-09-20 11:57
Duplicate of #1427

**Closed** 2022-09-20 11:57 UTC
Labels: duplicate, enhancement, area/vm
