### ISSUE TITLE
`extra_config:` doesn't work with dynamic blocks

### ISSUE THREAD

**Issue by selmison** [hashicorp/terraform-provider-vsphere#1346] opened 2021-02-18 10:04 UTC
The `extra_config` block doesn't work with `Dynamic Block` expression.

### Terraform Version
Terraform v0.14.5

### vSphere Provider Version
vSphere Provider v1.24.3

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
dynamic "extra_config"{
    for_each = var.is_debian ? [1] : []
    content {
      "guestinfo.metadata"                   = base64gzip(data.template_file.meta-data.rendered)
      "guestinfo.metadata.encoding" = "gzip+base64"
      "guestinfo.userdata"                    = base64gzip(data.template_file.user-data.rendered)
      "guestinfo.userdata.encoding"  = "gzip+base64"
    }
  }
```

### Expected Behavior
`terraform plan` should be executed successfully

### Actual Behavior
`terraform plan` returned the following error:

> Error: Invalid argument name
> 
>   on main.tf line 118, in resource "vsphere_virtual_machine" "vm":
>  118:       "guestinfo.metadata"         = base64gzip(data.template_file.meta-data.rendered)
> 
> Argument names must not be quoted.
> 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment] 2022-02-18 23:33
@selmison , Could you retest with the latest provider? If the same issue occurs can you provide a complete redacted plan/module as a Gist for reproduction?

Ryan Johnson
Staff II Solutions Architect | VMware, Inc

**Comment by tenthirtyam** [comment] 2022-03-18 23:38
Hi @selmison,

Could you retest with the latest provider? If the same issue occurs can you provide a complete redacted plan/module as a Gist for reproduction?

Ryan Johnson
Staff II Solutions Architect | VMware, Inc

**Comment by educrod** [comment] 2022-03-29 21:31
I have the same problem. Any new about this issue?

**Comment by educrod** [comment] 2022-03-29 21:36
Using previously-installed hashicorp/vsphere v2.1.1

**Comment by tenthirtyam** [comment] 2022-03-29 21:44
This issue is in the backlog at this time, please be sure to add a 👍 reaction to help influence  prioritization.

If you can provide a complete redacted plan/module as a Gist for reproduction, that would be helpful.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-04-18 22:57
The issue is currently pending closure. If you can provide a complete redacted plan/module as a Gist for reproduction, that would be very helpful and appreciated.

Thanks!

Ryan Johnson
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-07-20 23:02
Hi @selmison 👋 

There have been a few requests ([1](https://github.com/hashicorp/terraform-provider-vsphere/issues/1346#issuecomment-1045348726) [2](https://github.com/hashicorp/terraform-provider-vsphere/issues/1346#issuecomment-1072888319) [3](https://github.com/hashicorp/terraform-provider-vsphere/issues/1346#issuecomment-1080836406) [4](https://github.com/hashicorp/terraform-provider-vsphere/issues/1346#issuecomment-1082402038) [5](https://github.com/hashicorp/terraform-provider-vsphere/issues/1346#issuecomment-1101834840) ) for a redacted plan / module as a Gist for reproduction as this would assist in issue reproduction. 

At this time, this issue is being marked as `pending-closure` and will soon be closed if an example can not be provided for reproduction.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-07-30 13:21
Hi @educrod 👋 

You mentioned you were having the same issue. Can you provide a redacted plan / module as a Gist for reproduction as this would assist in issue reproduction?

Thanks.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-08-03 09:05
Marking this issue as `closed`.

If this issue is reproducible with the [latest](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest) version of the provider, we encourage creating a new issue with all the requested details and linking back to this one for added context. 

Thank you!

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Closed** 2022-08-03 09:06 UTC
Labels: bug, area/guest, not-reproduced
