### ISSUE TITLE
Terraform VMotion Issue

### ISSUE THREAD

**Issue by anu-allam** [hashicorp/terraform-provider-vsphere#1334] opened 2021-02-06 05:18 UTC
Terraform failed to migrate datastore. It says migration is successful but it is migrating only the configuration files and not the virtual disk (.vmdk)

**Comment by jweigand** [comment] 2021-02-06 12:10
Probably the same issue I reported in #1268  - change your provider version to 1.24.0 and it should work, I’m just having to sit on that version for now.

**Comment by anu-allam** [comment] 2021-02-06 18:11
Thank you for your response. So it works only with provider version 1.24.0 

Currently I have provider version 2.1.0 and Terraform version 0.14.5

**Comment by anu-allam** [comment] 2021-02-08 19:47
Thank you for your response.

**Comment by siwyroot** [comment] 2021-11-03 12:14
Hello, there is a W/A for this that works with 1.24.0 and with latest (probably all in between), for every disk instance you have in your virtual machine please add  "datastore_id" pointing with same info as for vm resource, here is example:

```
esource "vsphere_virtual_machine" "vm1" {
  name                 = var.vmname
  resource_pool_id     = data.vsphere_compute_cluster.cluster.resource_pool_id 
  datastore_id = data.vsphere_datastore.manual.id
  num_cpus = 1
  memory   = 2048
  guest_id = "other3xLinux64Guest"
  wait_for_guest_net_timeout = 0

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = "vmxnet3"
  }

  disk {
    datastore_id = data.vsphere_datastore.manual.id
    label            = "disk0"
    size             = var.c_size
    eagerly_scrub    = false
    thin_provisioned = true
    unit_number      = 0
  }
}
```

**Comment by tenthirtyam** [comment] 2022-02-04 00:26
Duplicate of #1268. Closing this issue and tracking using this originating issue.

Ryan

**Closed by tenthirtyam** 2022-02-04 00:26 UTC
Labels: bug, duplicate
