### ISSUE TITLE
Provider crashes after converting vm to template

### ISSUE THREAD

**Issue by indiantechsupporter** [hashicorp/terraform-provider-vsphere#2177] opened 2024-04-23 18:00 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.5, v1.8.1

### Terraform Provider

v2.7.0

### VMware vSphere

v7.0.3

### Description

After converting a vm provisioned with terraform to a template, the provider crashes. The only way to get it working again is to manually delete the vm from the state.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

```
resource "vsphere_virtual_machine" "hosting_team_iops_test" {
  name                       = "hosting-team-iops-test"
  resource_pool_id           = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id               = data.vsphere_datastore.vsan.id
  num_cpus                   = 4
  memory                     = 8196
  guest_id                   = "other3xLinux64Guest"
  wait_for_guest_ip_timeout  = 0
  wait_for_guest_net_timeout = 0
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    unit_number  = 0
    datastore_id = data.vsphere_datastore.vsan.id
    label        = "sda"
    size         = 30
  }
  disk {
    unit_number  = 1
    datastore_id = data.vsphere_datastore.vsan.id
    label        = "sdb"
    size         = 100
  }
  custom_attributes = tomap({
    (vsphere_custom_attribute.managed_by_terraform.id) = "true",
    # (vsphere_custom_attribute.terraform_directory.id)  = "${split("config", path.cwd)[1]}/${path.module}",
  })
  #   cdrom {
  #     datastore_id = data.vsphere_datastore.images.id
  #     path         = "c9d8e065-9c6f-7ab2-0b9d-b8cef656c942/ubuntu-22.04.4-live-server-amd64.iso"
  #   }
}

```

### Debug Output

[Link to Gist](https://gist.github.com/indiantechsupporter/a161c8e9f9d2f1a9f1cb841672310bcb)

### Panic Output

```
Stack trace from the terraform-provider-vsphere_v2.7.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x101c4b6]

goroutine 211 [running]:
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineRead(0xc000278c80, {0x11f84a0, 0xc000396090})
github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:452 +0x6d6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1724658?, {0x1724658?, 0xc0008a3920?}, 0xd?, {0x11f84a0?, 0xc000396090?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.32.0/helper/schema/resource.go:783 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002c1340, {0x1724658, 0xc0008a3920}, 0xc0004d6b60, {0x11f84a0, 0xc000396090})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.32.0/helper/schema/resource.go:1089 +0x529
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000251ce0, {0x1724658?, 0xc0008a3860?}, 0xc00059e940)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.32.0/helper/schema/grpc_provider.go:666 +0x4aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003d06e0, {0x1724658?, 0xc0008a30e0?}, 0xc0004b8f60)
github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov5/tf5server/server.go:774 +0x4c3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x14d7080, 0xc0003d06e0}, {0x1724658, 0xc0008a30e0}, 0xc000278900, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001aee00, {0x1724658, 0xc0008a3050}, {0x1729378, 0xc0000c2340}, 0xc000584fc0, 0xc0002db230, 0x2151548, 0x0)
google.golang.org/grpc@v1.61.0/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc0001aee00, {0x1729378, 0xc0000c2340}, 0xc000584fc0)
google.golang.org/grpc@v1.61.0/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.61.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 11
google.golang.org/grpc@v1.61.0/server.go:1040 +0x125

Error: The terraform-provider-vsphere_v2.7.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

I expect the provider to remove the virtual machine from the state or do nothing at all but not crash.

### Actual Behavior

Provider crashes.

### Steps to Reproduce

Create a vm with terraform, use the "template -> convert to template" function in vSphere and run a terraform plan e.g.

**Comment by tenthirtyam** [comment] 2024-04-28 23:57
Duplicate of #1180

Enhancement to support templates - conversion, state, etc.

**Closed** 2024-04-28 23:57 UTC
Labels: enhancement
