### ISSUE TITLE
Context Deadline reached with building VM with large disks

### ISSUE THREAD

**Issue by greeneg** [hashicorp/terraform-provider-vsphere#1415] opened 2021-05-19 20:11 UTC
### Terraform Version
0.13.5

### vSphere Provider Version
code checkout 875eb65

### Terraform Configuration Files

Here's our code snippet we're using for testing. Note that the modules are for network address allocation. Note that I gave the binary the 1.25.99 build number when I compiled it from check out 875eb65

```hcl
variable vsphere_admin {}
variable vsphere_admin_password {}
variable hco2cdj_token {}
variable vm_template {}
variable vm_network {}
variable naas_pass {}
variable naas_user {}
variable domain {}
variable os_version {}
variable root_password {}
variable correlation_id {}
variable vault_role_id {}
variable vault_secret_id {}

module windows {
  source                = "../"

  app_id                = 90306
  correlation_id        = var.correlation_id
  vipasswd              = var.vsphere_admin_password
  viuser                = var.vsphere_admin
  viserver              = "vcenter.example.com"
  vmfolder              = "GLOBAL-TERRAFORM-TEST/DEV"
  vdc                   = "edc1h1c1"
  vdc_ds                = "NAS0"
  vdc_cluster           = "pipeline-cluster"
  vdc_cpool             = "Terraform-Windows"
  vdc_network           = var.vm_network
  naas_api_host         = "nsg.app.example.com"
  naas_pass             = var.naas_pass
  naas_user             = var.naas_user
  location              = "site"
  zone                  = "internal"
  service               = "app"
  environment           = "prod"
  host_type             = "virtual"
  hostname_prefix       = "ito"
  domain                = var.domain
  vm_template           = var.vm_template
  server_ou             = "OU=Site,OU=Resources,DC=example,DC=com"
  disksinfo = [
    {
      size   = 1024,
      number = 1,
      label  = "DBStorage",
    }
  ]
  admin_users  = ["adjoinuser"]
  hco2cdj_token = var.hco2cdj_token
}

output node_name {
    value = module.windows.node_name
}
output host_name {
    value = module.windows.host_name
}
output ip_address {
    value = module.windows.ip_address
}
output app_id {
    value = module.windows.app_id
}
```

```hcl
// Random provider to generate GUID used for co-relation id during the provision process.  This unique GUID is being sent to all the calls made which require GUID.
resource random_password password {
  length      = 16
  special     = true
  upper       = true
  lower       = true
  number      = true
  min_upper   = 1
  min_lower   = 1
  min_numeric = 1
  min_special = 1
  override_special = "@-_.="
}

//Used to store interpolated data and avoid repeated interpolation symbols all over the code.
locals {
  adminpassword = random_password.password.result
  proxyidonly   = split("@", var.winrm_proxy_id)[0]
}

//Generate random and unique GUID (1 in a million duplicate can be found)
resource random_uuid correlationID {}

data vsphere_datacenter dc {
  name = var.vdc
}

data vsphere_datastore ds {
    name          = var.vdc_ds
    datacenter_id = data.vsphere_datacenter.dc.id
}

data vsphere_compute_cluster clstr {
  name          = "host/${var.vdc_cluster}"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data vsphere_resource_pool pool {
  name          = var.vdc_cpool
  datacenter_id = data.vsphere_datacenter.dc.id
}

data vsphere_virtual_machine tmplt {
  name          = var.vm_template
  datacenter_id = data.vsphere_datacenter.dc.id
}

module tfm_haas {
  source = "git@github.ford.com:NGSE/tfm_haas.git"

  location      = var.location
  environment   = var.environment
  prefix        = var.hostname_prefix
  haas_host     = var.naas_api_host
  haas_username = var.naas_user
  haas_password = var.naas_pass
  perl_path     = var.perl_path
}

module tfm_naas {
  source = "git@github.ford.com:NGSE/tfm_naas.git"

  location      = var.location
  zone          = var.zone
  service       = var.service
  environment   = var.environment
  host_type     = var.host_type
  node_name     = module.tfm_haas.hostname
  domain        = var.domain
  naas_api_host = var.naas_api_host
  naas_pass     = var.naas_pass
  naas_user     = var.naas_user
  perl_path     = var.perl_path

  providers = {
    external = external
  }
}

data vsphere_network ntwrk {
  name          = module.tfm_naas.apg
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource vsphere_virtual_machine Windows {
  wait_for_guest_net_timeout = -1
  name                       = module.tfm_haas.hostname
  num_cpus                   = var.cpu_count
  num_cores_per_socket       = var.cpu_count
  memory                     = var.ram_size
  resource_pool_id           = data.vsphere_resource_pool.pool.id
  folder                     = var.vmfolder
  datastore_id               = data.vsphere_datastore.ds.id
  guest_id                   = data.vsphere_virtual_machine.tmplt.guest_id
  scsi_type                  = data.vsphere_virtual_machine.tmplt.scsi_type

  network_interface {
    network_id   = data.vsphere_network.ntwrk.id
    adapter_type = data.vsphere_virtual_machine.tmplt.network_interface_types[0]
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.tmplt.disks.0.size
    eagerly_scrub    = var.eagerly_scrub
    thin_provisioned = var.thin_provisioned
  }

  dynamic disk {
    for_each = var.disksinfo
    content {
      unit_number      = disk.value.number
      label            = disk.value.label
      size             = disk.value.size
      thin_provisioned = var.thin_provisioned
      eagerly_scrub    = var.eagerly_scrub
    }
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.tmplt.id
    customize {
      timeout = 30
      windows_options {
        computer_name  = module.tfm_haas.hostname
        time_zone      = 35
        admin_password = local.adminpassword
        workgroup      = "workgroup"
        run_once_command_list = [
          "powershell.exe Set-ItemProperty HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters -Name 'NV Domain' -Type String -Value '${var.domain}' -Force",
          "powershell.exe Set-ItemProperty HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters -Name 'SyncDomainWithMembership' -Type DWord -Value 0 -Force",
        ]
      }
      network_interface {
        ipv4_address = module.tfm_naas.ip_address
        ipv4_netmask = module.tfm_naas.bitmask
      }
      ipv4_gateway    = module.tfm_naas.ip_gateway
      dns_suffix_list = [ module.tfm_naas.dns_search ]
      dns_server_list = [
        module.tfm_naas.dns01,
        module.tfm_naas.dns02
      ]
    }
  }
  depends_on = [random_password.password]

  extra_config = {
    "tools.upgrade.policy" = "manual"
  }
}
```

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "1.25.99"
    }
    null = {
      source  = "hashicorp/null"
      version = "2.1.2"
    }
    external = {
      source  = "hashicorp/external"
      version = "1.2.0"
    }
    http = {
      source  = "hashicorp/http"
      version = "1.2.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "2.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "2.3.0"
    }
  }
}

provider vsphere {
  user                 = var.viuser
  password             = var.vipasswd
  vsphere_server       = var.viserver
  allow_unverified_ssl = true
  vim_keep_alive       = 120
  api_timeout          = 45
}
provider external {}
provider http {}
provider local {}
provider null {}
```

### Debug Output

```
Error: 
WARNING:
There was an error performing post-clone changes to virtual machine "/edc1h1c1/vm/GLOBAL-TERRAFORM-TEST/DEV/ito120005":
error reconfiguring virtual machine: Post "https://vca01-aos.hosts.cloud.ford.com/sdk": context deadline exceeded
Additionally, there was an error removing the cloned virtual machine:
error destroying virtual machine: Post "https://vca01-aos.hosts.cloud.ford.com/sdk": context deadline exceeded

The virtual machine may still exist in Terraform state. If it does, the
resource will need to be tainted before trying again. For more information on
how to do this, see the following page:
https://www.terraform.io/docs/commands/taint.html

If the virtual machine does not exist in state, manually delete it to try again.


  on ../main.tf line 119, in resource "vsphere_virtual_machine" "Windows":
 119: resource vsphere_virtual_machine Windows {
```

### Expected Behavior

System should build with the disks as thick provision eager zero, without context deadline reached

### Actual Behavior

Machine gets destroyed by vCenter

### Steps to Reproduce

terraform apply the configuration

### Important Factoids

This is using the pre-released provider code that was patched recently. The patch does not appear to fix the issue

### References

There are other issues in the repo that cover much the same, I'll link to them shortly

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by koikonom** [comment] 2021-06-03 07:36
Hi @greeneg, thanks for reporting this issue!

Would it be possible to reproduce the issue with debug logs enabled? Set the `TF_LOG` environment variable to `DEBUG`, run the apply operation again, and attach the log to this issue.

**Comment by greeneg** [comment] 2021-07-26 01:24
I'll work on this later this week. We've been busy with getting deployments rolled out.....

**Comment by tenthirtyam** [comment] 2022-02-05 02:14
Duplicate of #1134.

**Ryan Johnson**
Staff II Solutions Architect
Cloud Infrastructure Business Group, VMware

**Closed** 2022-02-05 02:15 UTC
Labels: bug, duplicate
