### ISSUE TITLE
expected length of name to be in the range (1 - 80), got ...

### ISSUE THREAD

**Issue by patrick-hermann-sva** [hashicorp/terraform-provider-vsphere#1331] opened 2021-02-04 15:55 UTC
### Terraform Version
14.4
### vSphere Provider Version
1.24.3

### Affected Resource(s)
vm(s) cant be created.
hi my template path is too long (88). is it possible to configure the expected length of this resource inside the provider / tf config somehow? 

```
module "createdbyansible" {
  source = "git::https:/.../virtual-machines/vsphere-vm.git"
  vm_count = 1
  vsphere_vm_name = "ubuntu18_stgt_2021-02-04-test-vm"
  vsphere_vm_folder_path = "stuttgart-things/packer"
  vm_memory = 4096
  vm_disk_size = "32"
  vsphere_datacenter = "NetApp-HCI-Datacenter"
  vm_num_cpus = 4
  firmware = "bios"
  vsphere_datastore = "/NetApp-HCI-Datacenter/host/NetApp-HCI-Cluster-01/10.100.135.44/NetApp-HCI-Datastore-04"
  vsphere_resource_pool = "Resources"
  vsphere_network = "/NetApp-HCI-Datacenter/host/NetApp-HCI-Cluster-01/10.100.135.44/tiab-prod"
  vsphere_vm_template = "/NetApp-HCI-Datacenter/host/NetApp-HCI-Cluster-01/10.100.135.42/ubuntu18_stgt_2021-02-04"
  vm_ssh_user = var.vm_ssh_user
  vm_ssh_password = var.vm_ssh_password
}
```

**Comment by DI-DaveGoodine** [comment] 2021-10-14 20:36
Terraform Version
1.0.8

vSphere Provider Version
2.0

Affected Resource(s)
Plan to create/update a VM fails.

We just upgraded to the 2.0 provider, and are seeing this as well:
```
│ Error: expected length of name to be in the range (1 - 80), got /02-prod/vm/02p-sre/02p-sre-templates//base-20-04-ubuntu-20.04-amd64-231caa5eadc8
│
│   with module.backup-vm.data.vsphere_virtual_machine.template,
│   on .terraform/modules/backup-vm/main.tf line 35, in data "vsphere_virtual_machine" "template":
│   35:   name          = join("/", tolist([lookup(var.template-path, var.location), var.vsphere_vm_template]))
```

Would like to be able to configure this as well.

Thanks!

**Comment by tenthirtyam** [comment] 2021-11-01 03:08
@DI-DaveGoodine -

The max characters for a virtual machine name in vSphere is 80; therefore the code below would matches the supported max character length in vSphere:

https://github.com/hashicorp/terraform-provider-vsphere/blob/ee62ff06fdcc8b0ca6185a03f02fbc0b1430d31f/vsphere/virtual_machine_config_structure.go#L192-L198.

Therefore, regarding the vm naming, this is not a bug, but as designed to conform with the vSphere maximum length for a virtual machine name. The provider is merely enforcing the maximum for the name.

Ryan
@tenthirtyam

**Comment by tenthirtyam** [comment] 2021-11-01 03:08
@patrick-hermann-sva can you provide you configuration(s) that is failing.

Ryan

**Comment by tenthirtyam** [comment] 2022-01-13 00:39
@DI-DaveGoodine, in your example it appears that you are trying to find the template based on a specific folder path versus the template name in the path of the `datacenter_id`.

```console
/02-prod/vm/02p-sre/02p-sre-templates//base-20-04-ubuntu-20.04-amd64-231caa5eadc8
```

Ryan

**Comment by tenthirtyam** [comment] 2022-01-28 19:34
Hi @patrick-hermann-sva,

This issue is a duplicate of #1262 which raises this valid concern.  We'll link these issues and track a path to resolution in the originating issue.

Ryan

**Closed by tenthirtyam** 2022-01-28 19:34 UTC
Labels: bug, duplicate
