### ISSUE TITLE
domain_ou unable to find proper ou and dc

### ISSUE THREAD

**Issue by jcroma** [hashicorp/terraform-provider-vsphere#2209] opened 2024-06-05 10:17 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.8.4

### Terraform Provider

v2.8.1

### VMware vSphere

8.0.2.00300

### Description

Hi, I was excited to use new version of vsphere provider to use domain_ou since our domain requires adding it to be albe to join domain.
So, my script is creating virtual machine and I wanted to add domain:
```    customize {
      network_interface {
      }

      windows_options {
        computer_name                = "CompDomain"
        join_domain                  = "sensitive.com"
        domain_admin_user            = "domainUser"
        domain_admin_password        = "******"
        domain_ou                    = "OU=Workstations,OU=SDE,OU=Business Units,DC=sensitive,DC=com"
      }
    } 
```
   While I executed it returns with error:
   ` Error: error sending customization spec: A specified parameter was not correct: The Domain OU string must refer to an existing OU in your target Domain. Please don't specify any other values excepting OU and DC in it.`

![image](https://github.com/hashicorp/terraform-provider-vsphere/assets/35994590/6cbdaf7d-4f36-4d98-a741-1785fd028844)
Note that I was able to add any virtual machine by same user with command:
```
Add-computer -DomainName
#{domain}
-OUPath 'OU=Workstations,OU=SDE,OU=Business Units,DC=sensitive,DC=com' -Credential $credential -force -Options JoinWithNewName,AccountCreate -PassThru
```

### Affected Resources or Data Sources

resource "vsphere_virtual_machine" "vm" {}
│   with vsphere_virtual_machine.vm[0],
│   on main.tf line 48, in resource "vsphere_virtual_machine" "vm":
│   48: resource "vsphere_virtual_machine" "vm" {

### Terraform Configuration

```
variable "vm_count" {
  description = "Number of machines to create"
  type        = number
  default     = 1
}

variable "vm_name" {
  description = "Name of VM"
  type        = string
}

resource "vsphere_virtual_machine" "vm" {
  count            = var.vm_count
  name             = "${var.vm_name}-${count.index}"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = var.create_folder ? resource.vsphere_folder.folder[0].path : var.vm_resource_pool

  hv_mode                = "hvOn"
  scsi_type              = data.vsphere_virtual_machine.template.scsi_type
  cpu_hot_add_enabled    = true
  cpu_hot_remove_enabled = true
  firmware               = data.vsphere_virtual_machine.template.firmware
  nested_hv_enabled      = true

  num_cpus               = 4
  memory                 = 4048
  memory_hot_add_enabled = true


  guest_id          = "Guest"

  disk {
    label            = "disk0"
    size             = 300
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks[0].eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned

  }

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    linked_clone  = false

    customize {
      network_interface {
      }

      windows_options {
        computer_name         = "CompDomain"
        join_domain           = "sensitive.com"
        domain_admin_user     = "domainUser"
        domain_admin_password = "******"
        domain_ou             = "OU=Workstations,OU=SDE,OU=Business Units,DC=sensitive,DC=com"
      }
    }
  }
}
```
**I would go with that there is something wrong with space character**
### Debug Output

Provided in description

### Expected Behavior

Join to domain

### Actual Behavior

Error

### Steps to Reproduce

1. fill data required to communicate with vsphere
2. execute script with your data to join domain

**Comment by D1StrX** [comment] 2024-06-08 18:43
https://github.com/hashicorp/terraform-provider-vsphere/issues/2206 same issue

**Comment by D1StrX** [comment] 2024-06-08 18:49
The issue is indeed that it doesn't properly handle the space in _OU=ou name_

**Comment by tenthirtyam** [comment] 2024-06-08 23:00
Duplicate of #2206

**Closed** 2024-06-08 23:00 UTC
Labels: bug, needs-triage
