### ISSUE TITLE
Creating VMKernel NIC with services [ex: vSAN] enabled 

### ISSUE THREAD

**Issue by IreshMM** [hashicorp/terraform-provider-vsphere#1876] opened 2023-03-30 12:25 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Recently came across the requirement to provision VMKernel NIC with vSAN enabled but no argument relating to that was found in the doc.

### Use Case(s)

Constructing a vSAN cluster

### Potential Terraform Provider Configuration

```tf
resource "vsphere_vnic" "v1" {
  host      = data.vsphere_host.h1.id
  portgroup = vsphere_host_port_group.p1.name
  ipv4 {
    dhcp = true
  }
  enabled_services = ["vSAN"]
}
```

### References

https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/vnic

**Comment by tenthirtyam** [comment] 2023-03-30 12:42
Duplicate of #1594

**Comment by tenthirtyam** [comment] 2023-03-30 12:44
Duplicate of #1594 which is attached to PR #1855 planned for milestone v2.4.0.

**Closed as completed by tenthirtyam** 2023-03-30 12:44 UTC
Labels: enhancement

**Comment by IreshMM** [comment] 2023-03-30 13:01
Apologies for the duplicate. I'll be sure look for existing ones next time.
