### ISSUE TITLE
Imported virtual machine is powered on after first apply 

### ISSUE THREAD

**Issue by epostea** [hashicorp/terraform-provider-vsphere#1266] opened 2020-12-02 16:37 UTC
### Terraform Version
0.12.21

### vSphere Provider Version
1.24.2

### Affected Resource(s)
- `vsphere_virtual_machine`

### Expected Behavior

The virtual machine should not be powered on. Tried the same steps with `terraform-provider-vsphere_v1.16.1_x4` and the virtual machine is not powered on. 

### Actual Behavior

The virtual machine is powered on. 

### Steps to Reproduce

1. `terraform import <your virtual machine resource id>`
2. `terraform plan`
The result of the terraform plan is:
```
Terraform will perform the following actions:
~ vsphere_virtual_machine.vm_1
disk.0.keep_on_remove: "true" => "false"

Plan:
0 to add, 1 to change, 0 to destroy.
```
3. `terraform apply`

### References
* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by swacongne** [comment] 2021-02-17 10:30
Hi, 
Thanks for the great work on the vSphere provider: I'm using it for a large bank with great results. 
We have encountered exactly the same issue. Do we know if this bug is accepted and if it can be fixed / when?

**Comment by epostea** [comment] 2021-02-22 16:35
I was able to reproduce the issue using terraform 0.12.21, updating the ticket.

**Comment by tenthirtyam** [comment] 2022-01-30 05:57
This appears to have been addressed in pull request #1361 per the description but needs to be verified.

**Comment by tenthirtyam** [comment] 2022-02-02 00:02
I've been able to reproduce the issue with the following:

```console
❯ terraform version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.0.2
```

For the reproduction I used a cloud-init based Ubuntu 20.04 LTS virtual machine and successfully imported the resource.

```console
terraform import vsphere_virtual_machine.vm /m01-dc01/vm/workloads/ubuntu-cloud-init
vsphere_virtual_machine.vm: Importing from ID "/m01-dc01/vm/workloads/ubuntu-cloud-init"...
vsphere_virtual_machine.vm: Import prepared!
  Prepared vsphere_virtual_machine for import
vsphere_virtual_machine.vm: Refreshing state... [id=42025938-ae59-286b-31ed-e44623fdb72e]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

However, when running the first apply the virtual machine was powered on since the following changes were found:

```hcl
❯ terraform plan
vsphere_virtual_machine.vm: Refreshing state... [id=42025938-ae59-286b-31ed-e44623fdb72e]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
      - annotation                              = <<-EOT
            Version: v22.01
            Built on: 2022-01-27 16:48 UTC
            Built by: HashiCorp Packer 1.7.9
        EOT -> null
      ~ extra_config                            = {
          + "guestinfo.metadata"          = "aW5zdGFuY2UtaWQ6IGNsb3VkLXZtCmxvY2FsLWhvc3RuYW1lOiBjbG91ZC12bQpuZXR3b3JrOgogIHZlcnNpb246IDIKICBldGhlcm5ldHM6CiAgICBlbnMxOTI6CiAgICAgIGRoY3A0OiBmYWxzZQogICAgICBhZGRyZXNzZXM6CiAgICAgICAgLSAxNzIuMTYuMTEuMTkyLzI0CiAgICAgIGdhdGV3YXk0OiAxNzIuMTYuMTEuMQogICAgICBuYW1lc2VydmVyczoKICAgICAgICBhZGRyZXNzZXM6CiAgICAgICAgICAtIDE3Mi4xNi4xMS4xMQogICAgICAgICAgLSAxNzIuMTYuMTEuMTI="
          + "guestinfo.metadata.encoding" = "base64"
          + "guestinfo.userdata"          = "I2Nsb3VkLWNvbmZpZwoKdXNlcnM6CiAgLSBkZWZhdWx0CiAgLSBuYW1lOiByYWlucG9sZQogICAgcHJpbWFyeV9ncm91cDogcmFpbnBvbGUKICAgIHN1ZG86IEFMTD0oQUxMKSBOT1BBU1NXRDpBTEwKICAgIGdyb3Vwczogc3Vkbywgd2hlZWwKICAgIHNzaF9pbXBvcnRfaWQ6IE5vbmUKICAgIGxvY2tfcGFzc3dkOiB0cnVlCiAgICBzc2hfYXV0aG9yaXplZF9rZXlzOgogICAgLSBlY2RzYS1zaGEyLW5pc3RwNTIxIEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQTFNakVBQUFBSWJtbHpkSEExTWpFQUFBQ0ZCQUR3WFYzcmJSQ1d3aFNyNmFNa0h1a1Y1TzdPR0FFeVV0QWVyajJhbkpIbTNtd2JPeGxCVS91TzRmMEVMcW8yR0pjVEFMTUMwYUZyYnZ1OXFvbklINVZGN3dCQmZDUDFjUzVCOTJzVWFnVlY5bGRJL3VvODllLzdkVllDOW1hUHNGYVpxMkcwL1BMVTBoWktPb2hxOTlPeGMyUk1TaUphYWVuWC9oTnF4NXhZU2FLK0NBPT0gY29kZUByYWlucG9sZS5pbwo="
          + "guestinfo.userdata.encoding" = "base64"
        }
        id                                      = "42025938-ae59-286b-31ed-e44623fdb72e"
        name                                    = "ubuntu-cloud-init"
        tags                                    = []
        # (65 unchanged attributes hidden)


      + clone {
          + template_uuid = "4202ba98-c37a-a520-bebe-fe3315e143d8"
          + timeout       = 30
        }


        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

As a result, I needed to all thee following to the `vsphere_virtual_machine` resource to block the modifications

```hcl
  lifecycle {
    ignore_changes = [
      annotation,
      extra_config,
      imported,
      clone,
      disk[0].keep_on_remove,
    ]
  }
````

Once added, no changes were found that would require the virtual machine to power on.

```console
❯ terraform plan
vsphere_virtual_machine.vm: Refreshing state... [id=42025938-ae59-286b-31ed-e44623fdb72e]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no
changes are needed.
```

Perhaps the full state is not being imported?

@appilon, what do you think?

**Comment by tenthirtyam** [comment] 2022-02-15 21:55
Marking this issue as closed based on the previous comment and and addition set of tests today where I was unable to reproduce the issue for the first apply.

```console
❯ terraform version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.0.2
```

```console
% terraform import vsphere_virtual_machine.vm /m01-dc01/vm/workloads/ubuntu-cloud-init
vsphere_virtual_machine.vm: Importing from ID "/m01-dc01/vm/workloads/ubuntu-cloud-init"...
vsphere_virtual_machine.vm: Import prepared!
  Prepared vsphere_virtual_machine for import
vsphere_virtual_machine.vm: Refreshing state... [id=4202295e-b0cf-7575-552b-e89d3bfe9a98]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

```console
 % terraform plan               
vsphere_virtual_machine.vm: Refreshing state... [id=4202295e-b0cf-7575-552b-e89d3bfe9a98]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
      ~ extra_config                            = {
          + "guestinfo.metadata"          = "aW5zdGFuY2UtaWQ6IGh1Zwpsb2NhbC1ob3N0bmFtZTogaHVnCm5ldHdvcms6CiAgdmVyc2lvbjogMgogIGV0aGVybmV0czoKICAgIGVuczE5MjoKICAgICAgZGhjcDQ6IGZhbHNlCiAgICAgIGFkZHJlc3NlczoKICAgICAgICAtIDE3Mi4xNi4xMS4xOTMvMjQKICAgICAgZ2F0ZXdheTQ6IDE3Mi4xNi4xMS4xCiAgICAgIG5hbWVzZXJ2ZXJzOgogICAgICAgIGFkZHJlc3NlczoKICAgICAgICAgIC0gMTcyLjE2LjExLjExCiAgICAgICAgICAtIDE3Mi4xNi4xMS4xMg=="
          + "guestinfo.metadata.encoding" = "base64"
          + "guestinfo.userdata"          = "I2Nsb3VkLWNvbmZpZwoKdXNlcnM6CiAgLSBkZWZhdWx0CiAgLSBuYW1lOiByeWFuCiAgICBwcmltYXJ5X2dyb3VwOiByeWFuCiAgICBzdWRvOiBBTEw9KEFMTCkgTk9QQVNTV0Q6QUxMCiAgICBncm91cHM6IHN1ZG8sIHdoZWVsCiAgICBzc2hfaW1wb3J0X2lkOiBOb25lCiAgICBwYXNzd2Q6ICQ2JGpxb3hsUXlXMlJPeHNMSzQkUDNnR3AyQmYwRkNTTEFaVE5hRS9MWkJxU3N2VkFZWk5QTndUZWhYWmJNQWhSSmRLT2pOcXF5VVdWVVR3cWw5Q25oSFVscGlsdVd6SGxSMkRwVUtENC8="
          + "guestinfo.userdata.encoding" = "base64"
        }
        id                                      = "4202295e-b0cf-7575-552b-e89d3bfe9a98"
      ~ imported                                = true -> false
        name                                    = "ubuntu-cloud-init"
        tags                                    = []
        # (65 unchanged attributes hidden)


      + clone {
          + template_uuid = "4202ba98-c37a-a520-bebe-fe3315e143d8"
          + timeout       = 30
        }

      ~ disk {
          ~ keep_on_remove   = true -> false
            # (19 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if
you run "terraform apply" now.
johnsonryan@johnsonryan-a01 clone-template-linux-cloud-init % terraform apply -refresh-only
vsphere_virtual_machine.vm: Refreshing state... [id=4202295e-b0cf-7575-552b-e89d3bfe9a98]

No changes. Your infrastructure still matches the configuration.

Terraform has checked that the real remote objects still match the result of your most recent changes, and found no
differences.

Would you like to update the Terraform state to reflect these detected changes?
  Terraform will write these changes to the state without modifying any real infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Result: VM was still powered off.

If the issue persists with the solution provided and [the latest version of the provider](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest), please open a new issue and reference this issue for additional context.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.

**Closed by tenthirtyam** 2022-02-15 21:55 UTC
Labels: bug, needs-triage, acknowledged
