### ISSUE TITLE
Clone From template succeeded but linux customization failed

### ISSUE THREAD

**Issue by ShotgunSpider** [hashicorp/terraform-provider-vsphere#1202] opened 2020-09-03 17:31 UTC
### Terraform Version
 v0.13.2
### vSphere Provider Version
v1.23.0

### Affected Resource(s)

```hcl
variable "name_prefix" {
  default = "srvlb"
}
variable "offset" {
  default = 1
}
variable "start_ipv4_address" {
  default = 100
}
provider "vsphere" {
  user           = "user@vsphere.local"
  password       = "password"
  vsphere_server = "vcsa"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "DATACENTERr"
}
 
data "vsphere_datastore" "datastore" {
  name          = "datastore"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
 
data "vsphere_compute_cluster" "cluster" {
    name          = "Cluster"
    datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
 
data "vsphere_resource_pool" "pool" {
  name          = "Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
 
data "vsphere_network" "network" {
  name          = "network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
 
data "vsphere_virtual_machine" "template" {
  name          = "template-ubuntu-20.04"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "cloned_virtual_machine" {
    count			 = "1"
    name             = "${var.name_prefix}${format("%02d", count.index + 1 + var.offset)}"
    folder           = "vm"
    resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
    datastore_id     = "${data.vsphere_datastore.datastore.id}"
    firmware         = "${data.vsphere_virtual_machine.template.firmware}"
 
    num_cpus = 2
    memory   = 4096
    guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
 
    network_interface {
        network_id   = "${data.vsphere_network.network.id}"
        adapter_type = "vmxnet3"
    }
 
    disk {
        label            = "disk0"
        size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
        eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
        thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
    }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    
    customize {
      linux_options {
        host_name = "${var.name_prefix}${format("%02d", count.index + 1 + var.offset)}"
        domain    = "prod.com"
      }
	  network_interface {
        ipv4_address = "${format("10.0.0.%d", (count.index + 1 + var.offset + var.start_ipv4_address))}"
        ipv4_netmask = "24"
      }
 
      ipv4_gateway = "10.0.0.1"  
	  dns_suffix_list = ["prod.com"]
      dns_server_list = ["10.0.0.2"]
    }
  }
}
```

### Expected Behavior

Create new VM from template with customized IP and hostname

### Actual Behavior

I get the error message "An error occurred while customizing VM srvlb02. For details reference the log file <No Log> in the guest OS"

### Steps to Reproduce

1. terraform apply

### Important Factoids
I'm running vsphere 6.7 on essentials plus kit, maybe i'm missing some important APIs

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hungtran84** [comment] 2020-10-23 17:31
@ShotgunSpider : please check the log at sth like /var/log/vmware-imc/toolsDeployPkg.log . In my case, it shown me that perl command is missing. So, adding perl installation in the template solved my issue.

**Comment by tenthirtyam** [comment] 2021-10-30 14:37
@ShotgunSpider 

I suspect that this is more of an issue with your Ubuntu 20.04 template having a conflict between VM Guest Customization and cloud-init, which is installed by default in Ubuntu 20.04 LTS, rather than an issue with the provider.

Also, as @hungtran84 points out, for some Linux distributions _(e.g. RHEL and RHEL derivatives)_, `perl` must be installed alongside `open-vm-tools` for vm guest customizations to function.

That said, since this issue pertains to Ubuntu 20.04 I've taken your example and removed the count/offset, as seen below. However, my Ubuntu 20.04 LTS template is instantiated by Packer and sets the cloud-init data source to [VMware, OVF, none] order using cloud-init >= 21.3. That said, you could simply `apt-get remove cloud-init` from your template and retest.

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.0.2"
    }
  }
  required_version = ">= 1.0.9"
}

provider "vsphere" {
  vsphere_server       = "m01-vc01.rainpole.io"
  user                 = "administrator@vsphere.local"
  password             = "VMware1!"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = "m01-dc01"
}

data "vsphere_network" "network" {
  name          = "M - 172.16.11.0"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = "m01-cl01"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = "local-ssd-01"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
data "vsphere_content_library" "content_library" {
  name = "m01-lib01"
}

data "vsphere_virtual_machine" "template" {
  name          = "ubuntu-server-20-04-lts"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name                    = "gh-1202"
  folder                  = "vm/Lab"
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  num_cpus                = 2
  memory                  = 4096
  firmware                = "efi"
  efi_secure_boot_enabled = true
  guest_id                = data.vsphere_virtual_machine.template.guest_id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label = "disk0"
    size  = 60
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      linux_options {
        host_name = "gh-1202"
        domain    = "rainpole.io"
      }
      network_interface {
        ipv4_address = "172.16.11.100"
        ipv4_netmask = "24"
      }

      ipv4_gateway    = "172.16.11.1"
      dns_suffix_list = ["rainpole.io"]
      dns_server_list = ["172.16.11.11", "172.16.11.12"]
    }
  }
}
```

The results of the `terraform apply --auto-approve` are seen below...

```bash
> terraform apply --auto-approve
vsphere_virtual_machine.vm: Refreshing state... [id=42027b72-4f52-751d-1715-67cd2bbae3f3]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # vsphere_virtual_machine.vm has been deleted
  - resource "vsphere_virtual_machine" "vm" {
      - annotation                              = "Built by HashiCorp Packer on 2021-10-27 16:21 UTC." -> null
      - boot_delay                              = 0 -> null
      - boot_retry_delay                        = 10000 -> null
      - boot_retry_enabled                      = false -> null
      - change_version                          = "2021-10-30T14:13:02.547241Z" -> null
      - cpu_hot_add_enabled                     = false -> null
      - cpu_hot_remove_enabled                  = false -> null
      - cpu_limit                               = -1 -> null
      - cpu_performance_counters_enabled        = false -> null
      - cpu_reservation                         = 0 -> null
      - cpu_share_count                         = 2000 -> null
      - cpu_share_level                         = "normal" -> null
      - datastore_id                            = "datastore-11" -> null
      - default_ip_address                      = "172.16.14.134" -> null
      - efi_secure_boot_enabled                 = true -> null
      - enable_disk_uuid                        = false -> null
      - enable_logging                          = false -> null
      - ept_rvi_mode                            = "automatic" -> null
      - firmware                                = "efi" -> null
      - folder                                  = "Lab" -> null
      - force_power_off                         = true -> null
      - guest_id                                = "ubuntu64Guest" -> null
      - guest_ip_addresses                      = [
          - "172.16.11.100",
          - "172.16.14.134",
          - "fe80::250:56ff:fe82:2470",
        ] -> null
      - hardware_version                        = 19 -> null
      - host_system_id                          = "host-10" -> null
      - hv_mode                                 = "hvAuto" -> null
      - id                                      = "42027b72-4f52-751d-1715-67cd2bbae3f3" -> null
      - ide_controller_count                    = 2 -> null
      - latency_sensitivity                     = "normal" -> null
      - memory                                  = 4096 -> null
      - memory_hot_add_enabled                  = false -> null
      - memory_limit                            = -1 -> null
      - memory_reservation                      = 0 -> null
      - memory_share_count                      = 40960 -> null
      - memory_share_level                      = "normal" -> null
      - migrate_wait_timeout                    = 30 -> null
      - moid                                    = "vm-18026" -> null
      - name                                    = "gh-1202" -> null
      - nested_hv_enabled                       = false -> null
      - num_cores_per_socket                    = 1 -> null
      - num_cpus                                = 2 -> null
      - poweron_timeout                         = 300 -> null
      - reboot_required                         = false -> null
      - resource_pool_id                        = "resgroup-6046" -> null
      - run_tools_scripts_after_power_on        = true -> null
      - run_tools_scripts_after_resume          = true -> null
      - run_tools_scripts_before_guest_reboot   = false -> null
      - run_tools_scripts_before_guest_shutdown = true -> null
      - run_tools_scripts_before_guest_standby  = true -> null
      - sata_controller_count                   = 0 -> null
      - scsi_bus_sharing                        = "noSharing" -> null
      - scsi_controller_count                   = 1 -> null
      - scsi_type                               = "pvscsi" -> null
      - shutdown_wait_timeout                   = 3 -> null
      - swap_placement_policy                   = "inherit" -> null
      - sync_time_with_host                     = false -> null
      - sync_time_with_host_periodically        = false -> null
      - uuid                                    = "42027b72-4f52-751d-1715-67cd2bbae3f3" -> null
      - vapp_transport                          = [] -> null
      - vbs_enabled                             = false -> null
      - vmware_tools_status                     = "guestToolsRunning" -> null
      - vmx_path                                = "gh-1202/gh-1202.vmx" -> null
      - vvtd_enabled                            = false -> null
      - wait_for_guest_ip_timeout               = 0 -> null
      - wait_for_guest_net_routable             = true -> null
      - wait_for_guest_net_timeout              = 5 -> null

      - clone {
          - linked_clone  = false -> null
          - template_uuid = "4202e06d-335e-edd3-9c6a-fbce70848e37" -> null
          - timeout       = 30 -> null

          - customize {
              - dns_server_list = [
                  - "172.16.11.11",
                  - "172.16.11.12",
                ] -> null
              - dns_suffix_list = [
                  - "rainpole.io",
                ] -> null
              - ipv4_gateway    = "172.16.11.1" -> null
              - timeout         = 10 -> null

              - linux_options {
                  - domain       = "rainpole.io" -> null
                  - host_name    = "gh-1202" -> null
                  - hw_clock_utc = true -> null
                }

              - network_interface {
                  - ipv4_address = "172.16.11.100" -> null
                  - ipv4_netmask = 24 -> null
                  - ipv6_netmask = 0 -> null
                }
            }
        }

      - disk {
          - attach           = false -> null
          - controller_type  = "scsi" -> null
          - datastore_id     = "datastore-11" -> null
          - device_address   = "scsi:0:0" -> null
          - disk_mode        = "persistent" -> null
          - disk_sharing     = "sharingNone" -> null
          - eagerly_scrub    = false -> null
          - io_limit         = -1 -> null
          - io_reservation   = 0 -> null
          - io_share_count   = 1000 -> null
          - io_share_level   = "normal" -> null
          - keep_on_remove   = false -> null
          - key              = 2000 -> null
          - label            = "disk0" -> null
          - path             = "gh-1202/gh-1202.vmdk" -> null
          - size             = 60 -> null
          - thin_provisioned = false -> null
          - unit_number      = 0 -> null
          - uuid             = "6000C293-cbd0-15ea-5da5-6eeac0adaadf" -> null
          - write_through    = false -> null
        }

      - network_interface {
          - adapter_type          = "vmxnet3" -> null
          - bandwidth_limit       = -1 -> null
          - bandwidth_reservation = 0 -> null
          - bandwidth_share_count = 50 -> null
          - bandwidth_share_level = "normal" -> null
          - device_address        = "pci:0:7" -> null
          - key                   = 4000 -> null
          - mac_address           = "00:50:56:82:24:70" -> null
          - network_id            = "network-16" -> null
          - use_static_mac        = false -> null
        }
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these
changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "datastore-11"
      + default_ip_address                      = (known after apply)
      + efi_secure_boot_enabled                 = true
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "efi"
      + folder                                  = "vm/Lab"
      + force_power_off                         = true
      + guest_id                                = "ubuntu64Guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = (known after apply)
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 4096
      + memory_limit                            = -1
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "gh-1202"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 2
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-6046"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + template_uuid = "4202e06d-335e-edd3-9c6a-fbce70848e37"
          + timeout       = 30

          + customize {
              + dns_server_list = [
                  + "172.16.11.11",
                  + "172.16.11.12",
                ]
              + dns_suffix_list = [
                  + "rainpole.io",
                ]
              + ipv4_gateway    = "172.16.11.1"
              + timeout         = 10

              + linux_options {
                  + domain       = "rainpole.io"
                  + host_name    = "gh-1202"
                  + hw_clock_utc = true
                }

              + network_interface {
                  + ipv4_address = "172.16.11.100"
                  + ipv4_netmask = 24
                }
            }
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "<computed>"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "disk0"
          + path              = (known after apply)
          + size              = 60
          + storage_policy_id = (known after apply)
          + thin_provisioned  = true
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-1001"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
vsphere_virtual_machine.vm: Still creating... [30s elapsed]
vsphere_virtual_machine.vm: Still creating... [40s elapsed]
vsphere_virtual_machine.vm: Still creating... [50s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm: Creation complete after 1m2s [id=42029439-fcd6-55ad-097a-66143821b57a]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Which successfully results in the following deployment:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/7771363/139537109-96dbf6d7-703b-4b9b-9f74-b039d18d8150.png">

Therefore, it's my recommendation that this is not a bug with the provider.

Ryan
@tenthirtyam

Recommend: `close/not-a-bug`

**Comment by tenthirtyam** [comment] 2022-01-17 19:25
cc @iBrandyJackson - Recommend for closure.

**Comment by tenthirtyam** [comment] 2022-01-27 02:41
cc @iBrandyJackson and @appilon  - I'd like to suggest this issue for closure based on age of issue, solution / example response provided.

Ryan

**Comment by appilon** [comment] 2022-01-27 19:21
Closing based on suggestion, please feel free to open a new issue if needed.

**Closed by appilon** 2022-01-27 19:21 UTC
Labels: bug
