### ISSUE TITLE
`ept_rvi_mode` and `hv_mode` always attemp to update on apply

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-vsphere#1902] opened 2023-05-11 12:54 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.4.6

### Terraform Provider

v2.3.1 and v2.4.0

### VMware vSphere

v8.0.1

### Description

After a virtual machine is created using the provider, after running an apply again Terraform wants to update the virtual-machine in-place as the fields `ept_rvi_mode` and `hv_mode` are constantly being changed even without touching those fields.
It looks like that the provider is using one of `automatic`, `on` or `off`, where VSphere unsets the field to an empty string `""`.

As a work-around I can use the following block
```
lifecycle {
    ignore_changes = [
      ept_rvi_mode,
      hv_mode
    ]
  }
```

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

-

### Debug Output

-

### Expected Behavior

No changes

### Actual Behavior

```
# module.workers["worker-06"].vsphere_virtual_machine.main will be updated in-place
  ~ resource "vsphere_virtual_machine" "main" {
      + ept_rvi_mode                            = "automatic"
      + hv_mode﻿﻿                                 = "hvAuto"
         id                                     = "..."
        name                                    = "vm-01"
        tags                                    = []
        # (69 unchanged attributes hidden)
```

### Steps to Reproduce

Run a `terraform apply` immediatly followed by a new run of `terraform apply`

**Comment by uprightvinyl** [comment] 2023-05-12 05:48
Seeing the same behaviour; ESXi & vCenter 8.0.1, Terraform v1.4.6, vSphere provider v2.4.0.

**Comment by tenthirtyam** [comment] 2023-05-12 13:52
Both default to automatic. One option may be to set these to computed like was done for annotation recently but they would still use the validation. cc @appilon 

https://github.com/hashicorp/terraform-provider-vsphere/blob/29a4c6ce2e7723e3bbeb58c5f12d5292b82c1b6c/vsphere/virtual_machine_config_structure.go#L26-L36

https://github.com/hashicorp/terraform-provider-vsphere/blob/29a4c6ce2e7723e3bbeb58c5f12d5292b82c1b6c/vsphere/virtual_machine_config_structure.go#L127-L140

**Comment by captainfalcon23** [comment] 2023-08-01 07:29
Same issue encountered today with latest provider and latest Vmware vCenter 8.0.1.

**Comment by gmintoco** [comment] 2023-08-04 17:10
same issue for us with latest provider and vcenter 8

**Comment by kbpsec** [comment] 2023-08-25 08:13
Same here. We have reproduced this on vCenter 8 and esxi 8. If vCenter 8 with esxi 7 works fine.

**Comment by pramodsharma62** [comment] 2023-08-30 23:43
Any update on this? I am running into same issue with latest provider.

**Comment by DSI-BenThomas** [comment] 2023-09-06 19:20
Can confirm also hit the issues on vCenter 8U1a and ESXi 8U1a (VCF5)

**Comment by LargoUsagi** [comment] 2023-11-02 20:32
Can confirm this on hosts using ESXi and vCenter 8.0.2

**Comment by Hello-User** [comment] 2023-12-29 23:31
Still an issue, even after manually defining the fields.

Latest version of the provider.
vCenter 8.0.1 (build 21815093) and ESXi 8.0.2 (build 22380479).

**Comment by smhick** [comment] 2024-01-02 15:09
same issue for us with latest provider and vcenter 8

**Comment by micropbl4** [comment] 2024-01-05 11:23
We face the same problem:
Terraform v1.6.0
Terraform Provider v2.5.1
VMware vSphere v8.0.1

**Comment by nc-td** [comment] 2024-01-05 19:00
im hitting this too

**Comment by Aly-ona** [comment] 2024-01-11 10:28
We hit same issue with:
Terraform v1.3.7
registry.terraform.io/hashicorp/vsphere v2.6.0
esxi: 8.0.2 22380479
vcenter: 8.0.2.00000

**Comment by smooti** [comment] 2024-01-18 15:00
same issue

**Comment by Flumeded** [comment] 2024-01-30 20:38
Same issue
Workaround for now to add

lifecycle {
    ignore_changes = [hv_mode, ept_rvi_mode]
}
  
  to the resource

**Comment by tenthirtyam** [comment] 2024-04-17 19:46
@stoyan-hristov - can you look into this one as well?

**Comment by tenthirtyam** [comment] 2024-05-08 21:00
Reverted in 2.8.1. Reopening.

**Comment by spacegospod** [comment] 2024-05-15 10:08
Going to reintroduce the [fix](https://github.com/hashicorp/terraform-provider-vsphere/pull/2172) as a breaking change in the next major release

**Comment by DamienDaco** [comment] 2024-05-28 10:07
Vsphere provider  2.8.1
Vsphere 8.0.2.00300

I'm still having the issue, VM are rebooting.
I've implemented the workaround with the lifecycle from above.

Just to make sure, is 2.8.1 supposed to fix the issue, or am I missing something?

**Comment by spacegospod** [comment] 2024-05-30 08:32
> Vsphere provider 2.8.1 Vsphere 8.0.2.00300
> 
> I'm still having the issue, VM are rebooting. I've implemented the workaround with the lifecycle from above.
> 
> Just to make sure, is 2.8.1 supposed to fix the issue, or am I missing something?

Hey @DamienDaco 
The fix was released with 2.8.0 but it caused updates to running VMs created with older versions so we decided to issue a patch and revert this change in 2.8.1

We consider this fix to be a breaking change since it can interrupt running workloads because the update to the configuration triggers a power cycle on the VMs.

We try to allow breaking changes only on major releases, that is why the fix for this issue will likely land with v3.0.0

**Comment by tenthirtyam** [comment] 2024-06-12 01:47
**Research Note**: Was reported in https://github.com/hashicorp/terraform-provider-vsphere/issues/2202#issuecomment-2124459375 that this issue is not observed in vSphere 7. Verification reequired.

**Closed** 2024-06-26 17:00 UTC
Labels: bug
