### ISSUE TITLE
Faulty backing of Hard disk on creation

### ISSUE THREAD

**Issue by JesseDW01** [hashicorp/terraform-provider-vsphere#1728] opened 2022-08-09 13:50 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.4

### Terraform Provider

v2.2.0

### VMware vSphere

v6.7.0 u3

### Description

When creating a simple VM container with minimal infrastructure, the creation of a new Disk does not provide a valid backing path or vmdk.

### Affected Resources or Data Sources

`resource_vsphere_virtual_machine`

### Terraform Configuration

```hcl
provider "vsphere" {
  vsphere_server = var.vsphere_server
  user           = var.vsphere_user
  password       = var.vsphere_password
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = var.datacenter
}

data "vsphere_host" "host" {
  name          = "esxi1"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = "cluster1/Resources"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_host_virtual_switch" "CS-NET_vSwitch"{
  name = "CS-NET_vSwitch"
  host_system_id = data.vsphere_host.host.id
  network_adapters = ["vmnic3"]
  active_nics = ["vmnic3"]
  standby_nics = []
}

resource "vsphere_host_port_group" "CS-NET"{
  name = "CS-NET"
  host_system_id = data.vsphere_host.host.id
  virtual_switch_name = "CS-NET_vSwitch"
}

data "vsphere_network" "CS-NET"{
name          = "CS-NET"
datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "PriDC" {
  name             = "PriDC"
 #  host_system_id   = data.vsphere_host.host.id
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  
  num_cpus       = 2
  memory           = 8192

  guest_id         = "other3xLinux64Guest"
  network_interface {
    network_id = data.vsphere_network.CS-NET.id
  }
  disk {
  	label = "disk0"
        size  = 20
  }
}
```

### Debug Output

https://gist.github.com/JesseDW01/d48333460b2a50d60c01b45e595d75ec

### Expected Behavior

The VM boots like normal, Backing looks like:
![image](https://user-images.githubusercontent.com/20374018/183661518-3f452a98-7610-447d-9c94-f06a2f00f957.png)

### Actual Behavior

State
Failed - Unable to enumerate all disks.

Errors
Unable to enumerate all disks.
The file specified is not a virtual disk

Backing looks like so:
![image](https://user-images.githubusercontent.com/20374018/183661722-fb30b559-ca78-4f68-b707-237af1471883.png)
no path to vmdk

### Steps to Reproduce

Terraform Apply

**Comment by tenthirtyam** [comment] 2022-08-09 18:21
Duplicate of #1639.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Closed by tenthirtyam** 2022-08-09 18:21 UTC
Labels: bug, duplicate, needs-triage, acknowledged, area/vm, area/storage

**Comment by tenthirtyam** [comment] 2022-08-09 18:22
@JesseDW01 - This has been closed as a duplicate.

One quick question about your configuration - are you creating the VM from scratch w/o cloning and customizing from a template?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by JesseDW01** [comment] 2022-08-09 19:11
I want to create the VM from scratch and then use PXE for the OS deployment.
Also I don’t use a vCenter Server but a standalone ESXi.
