### ISSUE TITLE
resource vsphere_file  fails to upload VMDk files on ESXi host directly

### ISSUE THREAD

**Issue by sumitmaggo** [hashicorp/terraform-provider-vsphere#1296] opened 2020-12-29 08:31 UTC
### Terraform Version
Terraform v0.13.3

### vSphere Provider Version

- provider registry.terraform.io/hashicorp/vsphere v1.24.3

### Affected Resource(s)

- resource "vsphere_file"

### Terraform Configuration Files

```
$ cat main.tf
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "= 1.24.3"
    }
  }
}

provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter_name
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = "cluster1/Resources"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_file" "upload" {
  for_each = var.images

  datacenter       = var.vsphere_datacenter_name
  datastore        = var.vsphere_datastore_name

  source_file      = each.value
  destination_file = "generic/${basename(each.value)}"
  create_directories = true
}


$ cat terraform.tfvars
vsphere_datastore_name = "datastore1"
vsphere_user = "root"
vsphere_password = "<myESXiPassword>"
vsphere_server = "<myESXiHostIP>"

images = {
   "vmdk1" = "/tmp/CentOS-7-x86_64-GenericCloud.vmdk"
}

```

### Expected Behavior
VMDK file should have been uploaded to datastore on VMWare ESXi host.

### Actual Behavior
VMDK file fails to get uploaded to datastore on VMWare ESXi host.

```
$ terraform version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/vsphere v1.24.3

$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/vsphere versions matching "1.24.3"...
- Installing hashicorp/vsphere v1.24.3...
- Installed hashicorp/vsphere v1.24.3 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ terraform apply
data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_file.upload["vmdk1"] will be created
  + resource "vsphere_file" "upload" {
      + create_directories = true
      + datacenter         = "ha-datacenter"
      + datastore          = "datastore1"
      + destination_file   = "generic/CentOS-7-x86_64-GenericCloud.vmdk"
      + id                 = (known after apply)
      + source_file        = "/tmp/CentOS-7-x86_64-GenericCloud.vmdk"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vsphere_file.upload["vmdk1"]: Creating...
vsphere_file.upload["vmdk1"]: Still creating... [10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [20s elapsed]

Error: error Error caused by file /vmfs/volumes/5bd0b7d5-02d4a3bb-154a-ac162d77f63c/generic/CentOS-7-x86_64-GenericCloud.vmdk

  on main.tf line 33, in resource "vsphere_file" "upload":
  33: resource "vsphere_file" "upload" {

```

### Steps to Reproduce
Try to upload VMDK file to datastore on VMWare ESXi host using vsphere_file resource.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment] 2022-01-21 04:01
Appears to also be a duplicate of #1243.

cc @appilon and @iBrandyJackson fir review and confirmation.

**Comment by tenthirtyam** [comment] 2022-01-21 04:03
@sumitmaggo, may I suggest reviewing #1243 if this PR resolves the same and if so, link the issue?

Thanks,
Ryan

**Comment by sumitmaggo** [comment] 2022-01-21 07:57
@tenthirtyam Yes, #1243 appears to be a duplicate and this PR resolves the issue.

**Comment by appilon** [comment] 2022-01-24 20:10
Closing duplicate

**Closed by appilon** 2022-01-24 20:10 UTC
Labels: bug, duplicate
