### ISSUE TITLE
vApp properties not being set with OVF deployment with provider 1.24.1 and 1.24.2

### ISSUE THREAD

**Issue by blakewade** [hashicorp/terraform-provider-vsphere#1242] opened 2020-10-18 23:18 UTC
### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "1.24.2"
    }
  }
}

variable "vsphere_user" {
  type = string
}

variable "vsphere_password" {
  type = string
}

variable "vsphere_server" {
  type = string
}

variable "vsphere_insecure" {
  type = bool
  default = true
}

variable "vsphere_datacenter" {
  type = string
}

variable "vsphere_datastore" {
  type = string
}

variable "vsphere_resource_pool" {
  type = string
}

variable "vsphere_host_system" {
  type = string
}

variable "vsphere_network" {
  type = string
}

variable "vsphere_ovf_url" {
  type = string
}

provider "vsphere" {
  user                  = var.vsphere_user
  password              = var.vsphere_password
  vsphere_server        = var.vsphere_server
  allow_unverified_ssl  = var.vsphere_insecure
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_resource_pool" "pool" {
  name          = var.vsphere_resource_pool
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "host" {
  name          = var.vsphere_host_system
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "docker-hosts" {
  name             = "vsphere-provider-test01"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  datacenter_id    = data.vsphere_datacenter.dc.id
  host_system_id   = data.vsphere_host.host.id

  num_cpus = 4
  memory   = 4096
  guest_id = "other3xLinux64Guest"
  hv_mode  = "hvOff"

  disk {
    label = "disk0"
    size  = 20
  }

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  ovf_deploy {
    remote_ovf_url       = var.vsphere_ovf_url
    disk_provisioning    = "thin"
    ovf_network_map = {
      "nat" = data.vsphere_network.network.id
    }
  }

  vapp {
    properties = {
      "guestinfo.hostname" = "vsphere-provider-test01",
      "guestinfo.dns1" = "8.8.8.8",
      "guestinfo.dns2" = "8.8.4.4",
      "guestinfo.nic1.name" = "ens33",
      "guestinfo.nic1.ipaddress" = "192.168.0.10",
      "guestinfo.nic1.netmask" = "255.255.255.0",
      "guestinfo.nic1.gateway" = "192.168.0.1",
    }
  }
}

```

### Debug Output

https://gist.github.com/blakewade/b9874daed1732d27008558b7f09d034a

### Expected Behavior

The OVF is deployed and the values for the vApp properties are set

### Actual Behavior

No values for the vApp properties have been set

![image](https://user-images.githubusercontent.com/71611767/96388248-10191c80-11eb-11eb-9873-2e9d04d1fc86.png)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is currently working for vSphere Provider 1.24.0

![image](https://user-images.githubusercontent.com/71611767/96388409-f3311900-11eb-11eb-9ac7-c18be9ad01f8.png)

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by omniproc** [comment] 2020-10-24 08:32
Confirming

**Comment by seohs7** [comment] 2020-12-09 14:30
Hi, 

I'm trying to use your example and I'm stuck  referring to the OVF source. 
During the **apply**, when I use a remote URL (ex.: ) I got 

``` 
Error: the given ovf file https://192.168.1.10/folder/template%5fcicd%2ftst1%2dcicd%2dzaa%2d1/tst1%2dcicd%2dzaa%2d1%2eova?dcPath=LAB%252dVIRTU%252d01&dsName=esxlab0003%255fLocal is empty

```

Result with TF_LOG=Trace: 

```
vsphere_virtual_machine.docker-hosts: Creating...
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalApply
2020/12/09 16:24:27 [DEBUG] EvalApply: ProviderMeta config value set
2020/12/09 16:24:27 [DEBUG] vsphere_virtual_machine.docker-hosts: applying the planned Create change
2020/12/09 16:24:27 [TRACE] GRPCProvider: ApplyResourceChange
2020-12-09T16:24:27.035+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] setting computed for "guest_ip_addresses" from ComputedKeys
2020-12-09T16:24:27.035+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] setting computed for "vapp_transport" from ComputedKeys
2020-12-09T16:24:27.035+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] vsphere_virtual_machine (ID = <new resource>): Beginning create
2020-12-09T16:24:27.035+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] tagsClientIfDefined: No tags configured, skipping loading of tagging client
2020-12-09T16:24:27.041+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] VM is being deployed from ovf/ova template https://192.168.1.10/folder/template%5fcicd%2ftst1%2dcicd%2dzaa%2d1/tst1%2dcicd%2dzaa%2d1%2eova?dcPath=LAB%252dVIRTU%252d01&dsName=esxlab0003%255fLocal
2020-12-09T16:24:27.041+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Locating resource pool with ID resgroup-8
2020-12-09T16:24:27.055+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Resource pool found: resgroup-8
2020-12-09T16:24:27.056+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Locating folder at path "" relative to virtual machine root
2020-12-09T16:24:27.146+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Folder located: "/LAB-VIRTU-01/vm"
2020-12-09T16:24:27.146+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Locating host system ID host-24
2020-12-09T16:24:27.162+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Host system found: host-24
2020-12-09T16:24:27.163+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Locating datastore with ID "datastore-30"
2020-12-09T16:24:27.177+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.24.2_x4: 2020/12/09 16:24:27 [DEBUG] Datastore with ID "datastore-30" found
2020/12/09 16:24:27 [DEBUG] vsphere_virtual_machine.docker-hosts: apply errored, but we're indicating that via the Error pointer rather than returning it: the given ovf file https://192.168.1.10/folder/template%5fcicd%2ftst1%2dcicd%2dzaa%2d1/tst1%2dcicd%2dzaa%2d1%2eova?dcPath=LAB%252dVIRTU%252d01&dsName=esxlab0003%255fLocal is empty
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/09 16:24:27 [TRACE] EvalMaybeTainted: vsphere_virtual_machine.docker-hosts encountered an error during creation, so it is now marked as tainted
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalWriteState
2020/12/09 16:24:27 [TRACE] EvalWriteState: removing state object for vsphere_virtual_machine.docker-hosts
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/12/09 16:24:27 [TRACE] EvalApplyProvisioners: vsphere_virtual_machine.docker-hosts has no state, so skipping provisioners
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/09 16:24:27 [TRACE] EvalMaybeTainted: vsphere_virtual_machine.docker-hosts encountered an error during creation, so it is now marked as tainted
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalWriteState
2020/12/09 16:24:27 [TRACE] EvalWriteState: removing state object for vsphere_virtual_machine.docker-hosts
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalIf
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalIf
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalWriteDiff
2020/12/09 16:24:27 [TRACE] eval: *terraform.EvalApplyPost
2020/12/09 16:24:27 [ERROR] eval: *terraform.EvalApplyPost, err: the given ovf file https://192.168.1.10/folder/template%5fcicd%2ftst1%2dcicd%2dzaa%2d1/tst1%2dcicd%2dzaa%2d1%2eova?dcPath=LAB%252dVIRTU%252d01&dsName=esxlab0003%255fLocal is empty
2020/12/09 16:24:27 [ERROR] eval: *terraform.EvalSequence, err: the given ovf file https://192.168.1.10/folder/template%5fcicd%2ftst1%2dcicd%2dzaa%2d1/tst1%2dcicd%2dzaa%2d1%2eova?dcPath=LAB%252dVIRTU%252d01&dsName=esxlab0003%255fLocal is empty
2020/12/09 16:24:27 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.docker-hosts
2020/12/09 16:24:27 [TRACE] vertex "vsphere_virtual_machine.docker-hosts": visit complete
2020/12/09 16:24:27 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/12/09 16:24:27 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/vsphere\"] (close)" errored, so skipping
2020/12/09 16:24:27 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/12/09 16:24:27 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2020/12/09 16:24:27 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2020/12/09 16:24:27 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

Error: the given ovf file https://192.168.1.10/folder/template%5fcicd%2ftst1%2dcicd%2dzaa%2d1/tst1%2dcicd%2dzaa%2d1%2eova?dcPath=LAB%252dVIRTU%252d01&dsName=esxlab0003%255fLocal is empty

  on main.tf line 104, in resource "vsphere_virtual_machine" "docker-hosts":
 104: resource "vsphere_virtual_machine" "docker-hosts" {


2020/12/09 16:24:27 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/12/09 16:24:27 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-12-09T16:24:27.392+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/vsphere/1.24.2/linux_amd64/terraform-provider-vsphere_v1.24.2_x4 pid=6175
2020-12-09T16:24:27.393+0100 [DEBUG] plugin: plugin exited
```
have you ever seen this behavior?

Thanks.

**Comment by omniproc** [comment] 2020-12-09 15:09
@seohs7 

I've not seen the issue with the URL but this seems to be related to your setup. The URL doesn't look like it's pointing to an OVF / OVA file but to a html page but it's hard to tell just from the URL.
However, the issue here seems to be that the VAPP properties are not set. So the deploy part works. I was testing with a local OVA file and saw the same result (VAPP properties empy). I created another issue  here https://github.com/pulumi/pulumi-vsphere/issues/144 but the pulumi issue seems to be related to this issue here.

**Comment by seohs7** [comment] 2020-12-09 15:21
hello @omniproc, 
Thanks very much for your quick response. 
I have vApp properties created on the template: 

![image](https://user-images.githubusercontent.com/58572252/101648629-4b410a80-3a3a-11eb-9ddb-e03387c0da35.png)

is that what you are talking about? 

For the URL format, I will also check, but I can download the OVA using the same url with wget or using a browser, so I thought that my url works.

**Comment by omniproc** [comment] 2020-12-09 16:18
@seohs7 yes, right. Can you also specify values for the properties? Also: do you still get them populated when you try to change let's say the CPU count of the VM at the first run?

**Comment by techBeck03** [comment] 2020-12-17 23:16
I've recently run into this same issue and have narrowed it down to the `resourceVSphereVirtualMachinePostDeployChanges` function within the `resource_vsphere_virtual_machine` code.  My vapp properties are properly configured initially but then somewhere in this block of code they get erased:

```
cfgSpec.DeviceChange = virtualdevice.AppendDeviceChangeSpec(cfgSpec.DeviceChange, delta...)
log.Printf("[DEBUG] %s: Final device list: %s", resourceVSphereVirtualMachineIDString(d), virtualdevice.DeviceListString(devices))
log.Printf("[DEBUG] %s: Final device change cfgSpec: %s", resourceVSphereVirtualMachineIDString(d), virtualdevice.DeviceChangeString(cfgSpec.DeviceChange))

// Perform updates
if _, ok := d.GetOk("datastore_cluster_id"); ok {
	err = resourceVSphereVirtualMachineUpdateReconfigureWithSDRS(d, meta, vm, cfgSpec)
} else {
	err = virtualmachine.Reconfigure(vm, cfgSpec)
}
if err != nil {
	return resourceVSphereVirtualMachineRollbackCreate(
		d,
		meta,
		vm,
		fmt.Errorf("error reconfiguring virtual machine: %s", err),
	)
}

vmprops, err := virtualmachine.Properties(vm)
if err != nil {
	return err
}
```

If i comment out that code and build/use the provider using dev_overrides the vapp properties persist as expected.

<img width="2095" alt="Screen Shot 2020-12-17 at 4 50 15 PM" src="https://user-images.githubusercontent.com/11505043/102554974-6f7c9700-408b-11eb-86d9-4110ee152450.png">

Otherwise they are removed and i see a bunch of entries in the logs about vapp properties vanishing.

<img width="902" alt="Screen Shot 2020-12-17 at 5 02 58 PM" src="https://user-images.githubusercontent.com/11505043/102554781-0f85f080-408b-11eb-9318-5984d3f75865.png">

<img width="2105" alt="Screen Shot 2020-12-17 at 5 02 18 PM" src="https://user-images.githubusercontent.com/11505043/102555012-83c09400-408b-11eb-8920-69a3fa657b72.png">

**Comment by techBeck03** [comment] 2020-12-19 20:20
After thinking about this some more does it really make sense to call `resourceVSphereVirtualMachinePostDeployChanges` when deploying from an OVA/OVF?  You wouldn't typically deploy from an OVF/OVA AND do a bunch of hardware/OS customizations.  Isn't that typically done using deployment options and vapp properties?

You would though need to add VM power on to the end of the `resourceVsphereMachineDeployOvfAndOva` function if skipping `resourceVSphereVirtualMachinePostDeployChanges`.

Thanks!

**Comment by ron4all** [comment] 2020-12-19 21:39
in addition to vApp-properties not transferred to the deployed VM...

...at least these parameters are missing, too:
* num_cores_per_socket, num_cpus
* DRAM-Size ("memory")
which are specified in the "ovf"-File

and
* Network-Mappings
which are specified in the ".tf"-file - so the VM gets deployed without any Ethernet-NIC.

Moving to provider "1.24.0" solves the issues.

**Comment by techBeck03** [comment] 2020-12-19 22:21
@ron4all I believe this is due to the multiple `Reconfigure`calls on the virtual machine.  If you skip the `resourceVSphereVirtualMachinePostDeployChanges` call after the OVA/OVF deploys then the network interfaces will exist along with the hardware outlined by the deployment option (if using).  Otherwise that second `Reconfigure` seems to wipe out all of the hardware config defined in the OVA/OVF.

This is all a guess on my part though so i'll leave it to the maintainers of the provider to chime in.

Thanks!

**Comment by omniproc** [comment] 2020-12-20 10:54
> Isn't that typically done using deployment options and vapp properties?

You can not change the virtual hardware using vapp properties. Vapp properties are passed to the OS at boot time, they're not used to edit the virtual hardware of the VM. At least I'm unaware of such an option. You could change them by manually editing the ova / ovf but that really destorys the hole purpose of using ova/ovf in first place (downloaded, share-able vm packages that are "ready to be deployed")

**Comment by techBeck03** [comment] 2020-12-20 11:51
> > Isn't that typically done using deployment options and vapp properties?
> 
> You can not change the virtual hardware using vapp properties. Vapp properties are passed to the OS at boot time, they're not used to edit the virtual hardware of the VM. At least I'm unaware of such an option. You could change them by manually editing the ova / ovf but that really destorys the hole purpose of using ova/ovf in first place (downloaded, share-able vm packages that are "ready to be deployed")

Correct regarding vapp properties alone and this is why i said `deployment options and vapp properties`.  vApp properties are for customization while a `DeploymentOptionSelection` allows you to provide a list of selectable hardware configurations.  In my case i'm deploying vcsa which includes a number of different DeploymentOption values such as tiny, small, medium, large, xlarge.  This is a supported part of the DMTF OVF standard as far as I understand.

What I'm still confused about is how I can pass a deployment option value using this provider.  This should be a supported feature IMHO.

Thanks!

**Comment by ron4all** [comment] 2020-12-20 12:18
> 
> What I'm still confused about is how I can pass a deployment option value using this provider. This should be a supported feature IMHO.
> 
> Thanks!

If passing a "deployment-option" isn't possible right now, shouldn't an "enhancement"-request get filed to distinguish it from this topic?
//[IMHO - I'm setting up virtual Cisco-Routers and face the same issue not being able to pass the needed "Deployment"-Option (here: `Small`, `Medium`, `Large` or `Large + DRAM Upgrade`) [Blog: OFV-OVA-Properties](https://allones.de/2020/12/18/ovf-ova-properties/) - when my setup might move to production, I'll need more horsepower than the (default=)"Small"-Environment.

//just re-read the "issues"-list, there are already 2 threads addressing this:
[https://github.com/hashicorp/terraform-provider-vsphere/pull/1215](https://github.com/hashicorp/terraform-provider-vsphere/pull/1215)
[https://github.com/hashicorp/terraform-provider-vsphere/issues/1209](https://github.com/hashicorp/terraform-provider-vsphere/issues/1209)

For my opinion i'll proceed the discussion at 1209

**Comment by techBeck03** [comment] 2020-12-20 12:30
@ron4all 100% agree, however, it's worth mentioning the deployment option capability within this issue as a case for why it doesn't seem to make sense to call `resourceVSphereVirtualMachinePostDeployChanges` in its current form at the end of `resourceVsphereMachineDeployOvfAndOva` since it ultimately wipes the hardware configuration defined within the OVA/OVF along with all of the vApp properties (which is what this issue is referring to).

Thanks!

**Comment by omniproc** [comment] 2020-12-20 13:08
Don't you think that this would make is more confusing to use? We have a CPU and a memory property. If a user sets that, the expected outcome would be it's used. Of course behind the scenes the API might be different. But I don't see why a additional property DeploymentOptionSelection should be required just for this use case. The workflow would be "well, you can set the CPU using the CPU property, BUT if you use this, then you have to set it in a different way". From a user perspective this should all be abstrected away.

**Comment by techBeck03** [comment] 2020-12-20 13:19
> Don't you think that this would make is more confusing to use? We have a CPU and a memory property. If a user sets that, the expected outcome would be it's used. Of course behind the scenes the API might be different. But I don't see why a additional property DeploymentOptionSelection should be required just for this use case. The workflow would be "well, you can set the CPU using the CPU property, BUT if you use this, then you have to set it in a different way". From a user perspective this should all be abstrected away.

My personal opinion is that this should be a separate resource altogether.  This way you could deploy a vm from an ovf/ova and then call `vsphere_virtual_machine` to do additional changes.

It would also be cool to get this all working under a single resource but I think this could also lead to confusion when you mix deployment options with custom hardware changes all in the same definition.

I'm also far from a terraform expert or power user so please take that into consideration when reading my opinions :-)

**SIDE NOTE:** I was able to include my proposed workaround for this issue along with the proposed changes in [#1215](https://github.com/hashicorp/terraform-provider-vsphere/pull/1215) and was able to get vcsa deployed properly in my lab using the selected deployment option (i tested with multiple).  I'm currently publishing a custom provider for others to test if interested.

**Comment by ron4all** [comment] 2020-12-21 10:40
_This is a double-post - i'll post it to "issue 1209", too, where it belongs [IMHO]_
[https://github.com/hashicorp/terraform-provider-vsphere/issues/1209](https://github.com/hashicorp/terraform-provider-vsphere/issues/1209)

> 
> 
> Don't you think that this would make is more confusing to use? We have a CPU and a memory property. If a user sets that, the expected outcome would be it's used. Of course behind the scenes the API might be different. But I don't see why a additional property DeploymentOptionSelection should be required just for this use case. The workflow would be "well, you can set the CPU using the CPU property, BUT if you use this, then you have to set it in a different way". From a user perspective this should all be abstrected away.

well, good question: I never tried to specify memory/cpu/operating-system when deploying OVA/OVFs since those parameters are specified by the DeploymentOption-Setting within the OVF-XML.
* so i expect, other people will find it intuitive, too, to not specify things manually which are already specified within the OVA/OVF-Appliance.

For my opinion, it would be more confusing, to have to manually add these (redundant) information.

On the other hand - I won't work anyway - so
* we technically have to pass the deployment-option to the VM
Why?
* manually specified parameters are overwritten by the "DeploymentOption"-Parameters specified within the OVA/OVF

### Example
I've been adding `num_cpus` and `memory` to my ".tf"-file:
```hcl
resource "vsphere_virtual_machine" "csr1kv-10" {
  for_each = local.sites
...
  num_cpus = 4
  memory   = 8192

ovf_deploy {
    # /vmfs/
    #local_ovf_path = "/volumes/DS-SOFTWARE/iso/cisco/csr1000v-universalk9.16.09.01.ova"
    local_ovf_path = "C:\\TEMP\\csr1000v-universalk9.16.09.01.ova"
    disk_provisioning = "thin"
    ovf_network_map = {
        "GigabitEthernet1" = data.vsphere_network.mgmt_lan.id,
,...
    }
  }
...
```

### Result
This is getting deployed:
![grafik](https://user-images.githubusercontent.com/26636908/102767371-bdd9b080-437f-11eb-88d0-82f9cfaf4ae4.png)
According to the "Default-DeploymentOption":
```Powershell
Key                : DeploymentOption
Value              :
DefaultValue       : 1CPU-4GB
OvfTypeDescription : string["1CPU-4GB", "2CPU-4GB", "4CPU-4GB", "4CPU-8GB"]
Description        : Small
                     Minimal hardware profile - 1 vCPU, 4 GB RAM
                     Medium
                     Medium hardware profile - 2 vCPUs, 4 GB RAM
                     Large
                     Large hardware profile - 4 vCPUs, 4 GB RAM
                     Large + DRAM Upgrade
                     Large hardware profile (requires purchase of DRAM upgrade SKU) - 4 vCPUs, 8 GB RAM
```
### Finding
So the DeploymentOption takes precedence.
### Conclusion
When not passing the DeploymentOption to the vCenter it uses the "default DeplyomentOption" - in my case the 1CPU-4G/Memory"-Setting.

**The DeploymentOption-Parameter needs to be passed from the .tf-Script to the VM/vCenter.**

**Comment by techBeck03** [comment] 2020-12-21 14:13
Completely agree @ron4all that you wouldn't typically adjust the hardware specs outlined in the deployment option if a deployment option selection is defined.  The challenge here is you are creating the same type of resource in either case, a virtual machine.

## Proposed Solution

**IF** a deploymentOptionSelection is present in the OVF **THEN** the following should happen:

1) The state for this virtual machine should include an entry specifying it was deployed using a deployment option
2) All `ResourceType`(s) specified within the selected deployment option (or default if non is specified) should also be tracked with the vm state
3) By default, if a virtual machine is deployed using an OVF + deployment option then you are not allowed to change any resource definitions that overlap with `ResourceType`(s) specified in the OVF (which are now tracked within the resource state).  Attempting to do so should throw  a clear error  message explaining why it isn't allowed.
4) Optional:  Allow overrides to these `ResourceType`(s) with a specific flag.

I'll post this in [#1209](https://github.com/hashicorp/terraform-provider-vsphere/issues/1209) as well since it relates but i wanted to propose this here since I believe the cause for the vApp properties getting removed is the unnecessary call to `resourceVSphereVirtualMachinePostDeployChanges` when a deployment option is passed.

Thanks

**Closed** 2021-01-29 16:26 UTC
Labels: bug
