### ISSUE TITLE
ha_datastore_apd_response_delay units issue

### ISSUE THREAD

**Issue by BradCalvertHCA** [hashicorp/terraform-provider-vsphere#1438] opened 2021-06-30 17:34 UTC
It appears for the setting ha_datastore_apd_response_delay in vsphere_compute_cluster, the vSphere UI wants this setting in minutes, and this provider wants the setting in minutes, but vSphere actually saves it in seconds behind the scenes (the setting as exposed in PowerCLI is in seconds and is called VmTerminateDelayForAPDSec). So on a default settings brand new cluster, when the provider retrieves the setting during a TF plan, it comes back as 180 seconds instead of 3 minutes and triggers a reconfigure that would result in being set to 3 seconds instead of 180.

### Terraform Version
1.0.0

### vSphere Provider Version
2.0.1

### Affected Resource(s)
vsphere_compute_cluster

### Terraform Configuration Files

```hcl
resource "vsphere_compute_cluster" "clu" {
  for_each = { for obj in local.cluster_inv : "${obj.name}" => obj }

  datacenter_id = each.value.dc_moid
  name          = each.value.name
  host_managed  = true

  ha_enabled = true
  ha_host_monitoring = "enabled"
  ha_vm_component_protection = "enabled"
  ha_datastore_apd_response_delay = 3
}
```
### Expected Behavior
setting ```ha_datastore_apd_response_delay = 3``` (which is the vSphere and TF default should produce no action on a vSphere cluster set to the default.

### Actual Behavior
TF tries to set ```ha_datastore_apd_response_delay``` from 180 to 3 on a fresh cluster

```
# vsphere_compute_cluster.clu["CLUSTERNAME"] will be updated in-place
  ~ resource "vsphere_compute_cluster" "clu" {
      ~ ha_datastore_apd_response_delay                       = 180 -> 3
      ~ ha_vm_component_protection                            = "disabled" -> "enabled"
        id                                                    = "domain-c95409"
        name                                                  = "CLUSTERNAME"
        tags                                                  = []
        # (47 unchanged attributes hidden)
    }
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BradCalvertHCA** [comment] 2021-06-30 17:40
I supposed the quickest workaround here is just to change the documentation for the provider to say the unit is seconds. But that conflicts with what the UI asks for (but not what is saved to the actual setting).

**Comment by tenthirtyam** [comment] 2021-12-16 03:48
Hi @BradCalvertHCA,

It's also **`VmTerminateDelayForAPDSec`** here in the provider:

https://github.com/hashicorp/terraform-provider-vsphere/blob/231a12819af1048f89988a77e3216a6c2a6eb3e2/vsphere/resource_vsphere_compute_cluster.go#L1781

I think the best course of action is to update the both the **docs** _and_ **defaults** to align with the API spec for `180` and `seconds` vs enforcing an multiplier (e.g. `VmTerminateDelayForAPDSec: int32(d.Get("ha_datastore_apd_response_delay").(int)) * 60,`) to align with the UI.

https://github.com/hashicorp/terraform-provider-vsphere/blob/231a12819af1048f89988a77e3216a6c2a6eb3e2/vsphere/resource_vsphere_compute_cluster.go#L307-L312

https://github.com/hashicorp/terraform-provider-vsphere/blob/37fd52c400e2d7901c51c67ad683b2e7d06c6bf3/website/docs/r/ha_vm_override.html.markdown#L160

I'll discuss with the maintainers and take up the review, changes, and testing for this one for a PR.

Ryan

**Comment by tenthirtyam** [comment] 2021-12-20 04:12
Given that the API default for `VmTerminateDelayForAPDSec` is `180` seconds, it might be best to remove `Default: 3` from `ha_datastore_apd_response_delay` altogether and then update the doc that it's in seconds and that it uses the vSphere defaults when not specified.

Source: https://developer.vmware.com/apis/361/doc/vim.cluster.VmComponentProtectionSettings.html#vmTerminateDelayForAPDSec

**Comment by tenthirtyam** [comment] 2021-12-21 04:28
Duplicate of #1386.

**Closed** 2022-01-06 16:08 UTC
Labels: bug
