### ISSUE TITLE
`r/vsphere_content_library_item` upload stuck at 1%

### ISSUE THREAD

**Issue by vrvaderom** [hashicorp/terraform-provider-vsphere#1977] opened 2023-08-06 21:16 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.5.4

### Terraform Provider

v2.4.1

### VMware vSphere

v8.0.1

### Description

Importing a content library item via url is stuck at 1%, and then eventually fails.

Manual import requires accepting the certificate, and then proceeds correctly and import completes successfully.

Duplicate of #1558, however copy/paste of the working example from that issue does not work (the example provided here mimics the solution from the previous issue)

### Affected Resources or Data Sources

resource/vsphere_content_library_item

### Terraform Configuration

```terraform
terraform {
  required_version = "~> 1.5.0"
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "2.4.1"
    }
  }
}
provider "vsphere" {
  user                 = var.vcenter_user
  password             = var.vcenter_password
  vsphere_server       = "vcenter.fqdn"
  allow_unverified_ssl = true
}

resource "vsphere_datacenter" "ovh_datacenter" {
  name = "OVH"
}

data "vsphere_datastore" "iso_datastore" {
  name          = "esxi05-main-datastore"
  datacenter_id = vsphere_datacenter.ovh_datacenter.moid
}

resource "vsphere_content_library" "iso_content_library" {
  name            = "OS install images"
  description     = "Library for ISO images for OS installation"
  storage_backing = [data.vsphere_datastore.iso_datastore.id]
}

resource "vsphere_content_library_item" "ubuntu_22_04_server" {
  name        = "iso-linux-ubuntu-22-04-server-lts"
  description = "Ubuntu 22.04 Server LTS ISO image"
  type        = "iso"
  file_url    = "https://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso"
  library_id  = vsphere_content_library.iso_content_library.id

    depends_on = [
    vsphere_content_library.iso_content_library,
  ]
}
`

### Debug Output

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_content_library_item.content_library_item will be created
  + resource "vsphere_content_library_item" "content_library_item" {
      + description = "ubuntu-21.10"
      + file_url    = "https://releases.ubuntu.com/21.10/ubuntu-21.10-live-server-amd64.iso"
      + id          = (known after apply)
      + library_id  = "10cc4129-8da0-490b-a7c1-ed621a4e4204"
      + name        = "ubuntu-21.10"
      + type        = "iso"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vsphere_content_library_item.content_library_item: Creating...
vsphere_content_library_item.content_library_item: Still creating... [10s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [20s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [30s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [40s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [50s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [1m0s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [1m10s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [1m20s elapsed]
vsphere_content_library_item.content_library_item: Still creating... [1m30s elapsed]
╷
│ Error: The import of library item b7b5e44f-e39b-40ba-87f9-ef57d94d81fc has failed. Reason: Error transferring file ubuntu-21.10-live-server-amd64.iso from https://releases.ubuntu.com/21.10/ubuntu-21.10-live-server-amd64.iso. Reason: Server not trusted: certificate_unknown(46).
```

### Expected Behavior

Terraform exits cleanly after correctly importing the file

### Actual Behavior

Terraform fails with 
`Reason: Server not trusted: certificate_unknown(46).`

### Steps to Reproduce

Working against a setup VCenter, fill in the variables in the example, terraform init, then terraform apply -auto-approve

### Environment Details

Three server setup, One datacenter defined, one server runs the VCenter appliance and holds the content library, two more servers in a cluster.

Environment is setup from scratch, clean, no resource capacity issues or anything.

### References

#1558

**Comment by tenthirtyam** [comment] 2023-08-06 22:23
Duplicate of #1879

**Closed** 2024-03-07 03:52 UTC
Labels: bug, duplicate, needs-triage, area/content-library
