### ISSUE TITLE
Document vsphere_virtual_machine sata_controller_count and scsi_controller_count that are missing

### ISSUE THREAD

**Issue by Shocktrooper** [hashicorp/terraform-provider-vsphere#2109] opened 2024-01-10 22:09 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

When trying to add more than 14 disks I ran into an issue where there was only 1 SCSI controller.  I was looking at where to add it in the `vsphere_virtual_machine` resource but noted that it was only listed in 1 place on the entire page.  This mention was not an attribute definition but a description paragraph saying that it could be set.  When looking around the only controller count defined in the resource is the `ide_controller_count`.  `scsi_controller_count` and `sata_controller_count` are not defined inside of the resource at all

Picture with only ide controller count defined
![image](https://github.com/hashicorp/terraform-provider-vsphere/assets/2646851/3ae3443b-0619-4731-aba7-42d1d20a0153)

Picture with only mentions of  `scsi_controller_count` and `sata_controller_count` but no other mention of these are in the documentation
![image](https://github.com/hashicorp/terraform-provider-vsphere/assets/2646851/6b5b68f4-4b05-4b2a-a198-36a5cf842b3f)

### Use Case(s)

Documentation update

**Comment by tenthirtyam** [comment] 2024-03-07 03:47
Duplicate of #2146

**Closed by tenthirtyam** 2024-03-07 03:47 UTC
Labels: documentation
