### ISSUE TITLE
Add support for [vsphere_vnic service(vSAN etc.) configurable]

### ISSUE THREAD

**Issue by zxinyu08** [hashicorp/terraform-provider-vsphere#1802] opened 2022-12-14 09:11 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently the service of VMkernal Adapter could not be configured in `r/vsphere_vnic`. It's a blocker for creating a whole healthy vSAN cluster. There is a network partition health issue if vSAN service is not enabled. Hence, we need enhance `r/vsphere_vnic` to support different services configured.

### Use Case(s)

During vSAN cluster creation, vSAN service of VMkernal Adapter on each host should be enabled.

**Comment by tenthirtyam** [comment] 2022-12-14 12:46
Duplicate of #1594

**Comment by tenthirtyam** [comment] 2022-12-14 14:03
Closing in favor of #1594 for the same topic.

**Closed** 2022-12-15 00:53 UTC
Labels: enhancement, area/networking
