### ISSUE TITLE
Import Roles and Permissions

### ISSUE THREAD

**Issue by gazm81** [hashicorp/terraform-provider-vsphere#1231] opened 2020-10-12 23:24 UTC
### Description

Would love the ability to import Roles and permissions. The newly added resource doesn't have import as yet.
Similar to other vsphere resources

### Potential Terraform Configuration

```sh
terraform import vpshere_role.role {role id}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment] 2022-01-13 01:06
Duplicate of #1102.

**Comment by iBrandyJackson** [comment] 2022-01-13 18:13
Closing issue due to being a duplicate - future work with this feature request will be tracked with #1102

**Closed by iBrandyJackson** 2022-01-13 18:13 UTC
Labels: enhancement
