### ISSUE TITLE
OVA deployment fails when host_system_id is not set but with resource_pool_id

### ISSUE THREAD

**Issue by ksamoray** [hashicorp/terraform-provider-vsphere#2126] opened 2024-01-30 13:30 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.1

### Terraform Provider

v2.6.1

### VMware vSphere

v7.0.3

### Description

The provider allows creation of `vsphere_virtual_machine` resources without specification of `host_system_id` attribute.
However while importing an OVA, `terraform plan` command succeeds but apply fails with
```
Error: while extracting OVF parameters: host system ID is required for ovf deployment
```

As ovftool allows OVA import with no host specification, it seems like a provider limitation. Also the documentation specifies that either `resource_pool_id` or `host_system_id` should suffice.

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

```
resource "vsphere_virtual_machine" "my_vm" {
  count                     = var.INSTANCE_COUNT
  provider                  = vsphere.penv-vsphere
  name                      = format("myvm-%d--%s", count.index, var.ENV_NAME)
  datacenter_id             = data.vsphere_datacenter.penv_datacenter.id
  resource_pool_id          = data.vsphere_compute_cluster.penv_cluster.resource_pool_id
  datastore_id              = data.vsphere_datastore.penv_datastore.id
//  host_system_id            = data.vsphere_host.penv_host.id
  folder                    = format("deployment--%s", var.ENV_NAME)
  num_cpus                  = 8
  memory                    = 32768
  wait_for_guest_ip_timeout = 10
  network_interface {
    network_id = data.vsphere_network.penv_mgt_network.id
  }

  ovf_deploy {
    allow_unverified_ssl_cert = true
    remote_ovf_url            = var.OVA_URL
    disk_provisioning         = "thin"
    ip_protocol               = "IPv4"
    ovf_network_map           = {
      "Network 1" = data.vsphere_network.penv_mgt_network.id
    }
  }
  vapp {
    properties = {
.
.
.
    }
  }
  lifecycle {
    ignore_changes = [
      vapp
    ]
  }
}
```

### Debug Output

```
2024-01-30T13:22:46.440Z [ERROR] provider.terraform-provider-vsphere_v2.6.1_x5: Response contains error diagnostic: diagnostic_severity=ERROR tf_proto_version=5.4 tf_req_id=1490f853-1a9a-96e8-d12f-7df3fa9be496 diagnostic_summary="while extracting OVF parameters: host system ID is required for ovf deployment" @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto tf_rpc=ApplyResourceChange diagnostic_detail="" tf_provider_addr=provider tf_resource_type=vsphere_virtual_machine timestamp=2024-01-30T13:22:46.440Z
```

### Expected Behavior

VM should deploy successfully

### Actual Behavior

Execution results with:
```
Error: while extracting OVF parameters: host system ID is required for ovf deployment
```

### Steps to Reproduce

Deploy a VM with `resource_pool_id` set but without `host_system_id`.

**Comment by tenthirtyam** [comment] 2024-01-30 14:14
Duplicate of #1284

**Closed by tenthirtyam** 2024-01-30 14:14 UTC
Labels: bug, needs-triage
