### ISSUE TITLE
Add support for vsphere_vnic to enable the vMotion

### ISSUE THREAD

**Issue by Thiyagu025** [hashicorp/terraform-provider-vsphere#1818] opened 2023-01-17 16:09 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

I have created the VMkernel adapter using resource "vsphere_vnic" but there is no option to enable the vMotion 

![image](https://user-images.githubusercontent.com/122903930/212950943-e96cb4ae-46ba-46c4-8c74-434ccdfcb267.png)

### Use Case(s)

creating VMkernel adapter in vSphere

###################### vMotion VMNIC Creation #####################
resource "vsphere_vnic" "v1" {
 count = "${length(var.ESXi_01)}"
 host = "${element(data.vsphere_host.hosts.*.id, count.index)}"
  distributed_switch_port = data.vsphere_distributed_virtual_switch.TEST01-vDS02.id
  distributed_port_group  = vsphere_distributed_port_group.TEST01-MGMT-pg2.id
  mtu = "9000"
  ipv4 {
   ip = "${lookup(var.vMotionIP_01,count.index)}"
   netmask = var.vMotionIpnet_01
   }
   netstack                = "defaultTcpipStack"
 }

**Comment by tenthirtyam** [comment] 2023-01-17 16:11
Duplicate of #1594

**Closed** 2023-01-17 16:11 UTC
Labels: duplicate, enhancement
