### ISSUE TITLE
vsphere vm with two networks and two nics

### ISSUE THREAD

**Issue by tfiedler** [hashicorp/terraform-provider-vsphere#1328] opened 2021-02-03 22:13 UTC
### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data "vsphere_network" "net1" {
  name          = "somenetwork"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "net2" {
  name          = "somothernetwork"
  datacenter_id = data.vsphere_datacenter.dc.id
}
```

Then in the vsphere_virtual_machine section

```hcl
resource "vsphere_virtual_machine" "vm" {

 network_interface {
    network_id = data.vsphere_network.net1.id
    adapter_type = "vmxnet3"
  }

  network_interface {
    network_id = data.vsphere_network.net2.id
    adapter_type = "vmxnet3"
  }
```

And in customization

```hcl
network_interface {
  ipv4_address = "192.168.102.87"
  ipv4_netmask = 24
  dns_domain = var.dns_domain
  dns_server_list = var.dns_server_list
}

network_interface {
  ipv4_address = "10.3.1.19"
  ipv4_netmask = 24
}
```

### Debug Output

```
Error: POST https://cloud9.lab.yolo.com/rest/com/vmware/vcenter/ovf/library-item/id:937fe71e-1b83-4e11-8097-b5b8e91cc317?~action=deploy: 500 Server Error

  on main.tf line 70, in resource "vsphere_virtual_machine" "vm":
  70: resource "vsphere_virtual_machine" "vm" {
  ```

### Expected Behavior
Id have expected that two nics get created with the attributes in the config.

### Actual Behavior
Error 500 from server (vcenter)

### Important Factoids
Im not sure if this is important but this is getting deployed from a content library ovf, The ovf this is being pulled rom only has 1 nic, and I suspect thats what Im running into. Im unsure how to resolve it.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment] 2022-01-17 19:19
Based on the debug output the source is an OVF from the content library.

```console
POST https://cloud9.lab.yolo.com/rest/com/vmware/vcenter/ovf/library-item/id:937fe71e-1b83-4e11-8097-b5b8e91cc317?~action=deploy: 500 Server Error
```

Does the originating OVF Template have two NICs? If note, per the VMware vSphere product documentation, which compares the use of VM Templates vs OVF Templates in Content Library:

> _"During the deployment of an OVF template, only guest OS customization is supported. **Hardware customization is not supported**."_

Reference: [The VM Template as a Content Library Item](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-CA4478D8-EC1B-47AD-B48E-38CD26B489FF.html)

Duplicate of #1345 and similar to #1441.

Regards,
Ryan

cc @appilon and @iBrandyJackson for review.

**Comment by appilon** [comment] 2022-01-28 20:43
Closing duplicate, please open a new issue if the issue persists.

**Closed by appilon** 2022-01-28 20:43 UTC
Labels: bug, duplicate, waiting-response
