### ISSUE TITLE
Unable to upload the vmdk file when the destination folder doesnt exist 

### ISSUE THREAD

**Issue by Kishanbhatk** [hashicorp/terraform-provider-vsphere#1587] opened 2022-02-14 11:19 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

0.13.3

### Terraform Provider

v2.0.2

### VMware ESXi

v7.0.2

### Description

I have used the source code of version v2.0.2 terraform vmware provider and built a plugin and used that plugin to perform instantiation . I have not done any modification . I found that I am unable to upload the vmdk when the destination directory is not present . But I am able to upload the iso .

### Affected Resources

`resource/vsphere_file`

### Terraform Configuration

```hcl
resource "vsphere_file" "upload" {

  datacenter = data.vsphere_datacenter.datacenter.id
  datastore  = var.vsphere_datastore_name

  source_file        = "/home/kishan/file.vmdk"
  destination_file   = "source_files/file.vmdk"
}
```

### Debug Output

```console
vsphere_file.upload["vmdk1"]: Still creating... [10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m30s elapsed]
vsphere_file.upload["vmdk1"]: Creation complete after 3m36s [id=[datastore1] ha-datacenter/source_files/file.vmdk]

vsphere_file.upload["vmdk1"]: Still creating... [4m40s elapsed]

Error: error File /vmfs/volumes/5ff5a927-3c8bedec-1ea5-e4434b298064/tfm-temp-457776264/file.vmdk was not found
```

### Expected Behavior

File should be uploaded properly

### Actual Behavior

Throws error

**Comment by tenthirtyam** [comment] 2022-02-14 12:03
Hi @Kishanbhatk,

This is a known issue and is resolved in pull request #1409. The fix will be in the next release of the provider.

Ryan

**Comment by Kishanbhatk** [comment] 2022-02-16 05:35
Hi I picked the latest code changes and built a plugin out of it , this issue is thrown only when the destination directory doesn't exist , It will work fine when the destination directory exist . This issue is only seen in vmdk

**Comment by tenthirtyam** [comment] 2022-02-16 05:45
You can also add `create_directories = true` as an option in the event the directories may not already exist.

Ryan

**Comment by Kishanbhatk** [comment] 2022-02-16 06:03
But create_directories option will throw error if it already exists , Need a functionality in such a way that directory needs to be created only if it doesnt exist otherwise it should not create . For time being I have modified the create_directories functionality according to my convenience to upload vmdk https://github.com/Kishanbhatk/terraform-provider-vsphere/commit/cea3a8ecae6f4aa16151beb9945ef09594ed1712

**Comment by Kishanbhatk** [comment] 2022-02-16 06:06
for ISO uploads I dont require create_directories option it will successfully upload with the latest change, but this issue is only seen in vmdk uploads with the latest change

**Comment by tenthirtyam** [comment] 2022-02-16 06:14
Reopening to review again before next release.

Ryan

**Comment by Kishanbhatk** [comment] 2022-03-02 15:13
Thank you @tenthirtyam

**Comment by Kishanbhatk** [comment] 2022-03-07 06:17
Hi @tenthirtyam  tried with the v2.1.0 still I am facing the issue , the destination folder is not getting created and once again I end up getting the error saying , 
 
 error File /vmfs/volumes/61dd1c66-77ccdf2e-58a4-c4346bb92f8c/tfm-temp-396211167/file.vmdk was not found

  on main.tf line 79, in resource "vsphere_file" "upload":
  79: resource "vsphere_file" "upload" {

**Comment by tenthirtyam** [comment] 2022-03-07 10:36
Please reopen the issue and attach the step-by-step details and any configurations. In our most recent exhaustive testing this was working as expected.

Thanks!

**Comment by Kishanbhatk** [comment] 2022-03-07 11:47
Okay I will attach the main.tf , variables.tf and terraform.tfvars files in text format for reference ,

[test-terraform.tfvars.txt](https://github.com/hashicorp/terraform-provider-vsphere/files/8197409/test-terraform.tfvars.txt)
[text-main.tf.txt](https://github.com/hashicorp/terraform-provider-vsphere/files/8197412/text-main.tf.txt)
[text-variables.tf.txt](https://github.com/hashicorp/terraform-provider-vsphere/files/8197413/text-variables.tf.txt)

**Comment by Kishanbhatk** [comment] 2022-03-07 11:48
When I try to run that above configuration file , I will get 

data.vsphere_datacenter.datacenter: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
vsphere_file.upload["vmdk1"]: Creating...
vsphere_file.upload["vmdk1"]: Still creating... [10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [3m20s elapsed]

Error: error File /vmfs/volumes/61dd1c66-77ccdf2e-58a4-c4346bb92f8c/tfm-temp-377859545/file.vmdk was not found

  on main.tf line 32, in resource "vsphere_file" "upload":
  32: resource "vsphere_file" "upload" {

**Comment by tenthirtyam** [comment] 2022-03-07 11:55
Does the destination directory path `source_files` exist before the run?

If not, set `create_directories = true`.

**Comment by tenthirtyam** [comment] 2022-03-07 12:26
I'll take a look at the scenarios again in the coming weeks. 

In the meantime, if you want to submit a pull request with any recommendations, please refer to the CONTRIBUTING.md.

Ryan

**Comment by Kishanbhatk** [comment] 2022-03-07 12:47
When the image is ISO and not the VMDK then it will upload successfully ,
The terraform.tfvars where ISO file is used instead of VMDK 
[test-terraform.tfvars.txt](https://github.com/hashicorp/terraform-provider-vsphere/files/8197783/test-terraform.tfvars.txt)

**Comment by Kishanbhatk** [comment] 2022-03-07 12:48
This is the output when ISO is used , 

data.vsphere_datacenter.datacenter: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
vsphere_file.upload["vmdk1"]: Creating...
vsphere_file.upload["vmdk1"]: Still creating... [10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m40s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [1m50s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m0s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m10s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m20s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m30s elapsed]
vsphere_file.upload["vmdk1"]: Still creating... [2m40s elapsed]
vsphere_file.upload["vmdk1"]: Creation complete after 2m47s [id=[datastore1] ha-datacenter/source_files/file.iso]

**Comment by Kishanbhatk** [comment] 2022-03-07 12:49
For temporary work around I have modified the create_directories usage like this ,
https://github.com/Kishanbhatk/terraform-provider-vsphere/commit/cea3a8ecae6f4aa16151beb9945ef09594ed1712

**Comment by tenthirtyam** [comment] 2022-03-07 12:53
Thanks, I'll refer to this when I review the issue next.

Ryan

**Comment by tenthirtyam** [comment] 2022-03-11 18:21
I'm struggling to see the issue here and the need for the workaround.

If I use the following configuration , I can:
- ✅ successfully upload a VMDK fine when a directory **does not** exist - it's created.
-  ✅ successfully upload a VMDK fine when the directory **does** exist already without any issues. 

```hcl
resource "vsphere_file" "gh-1614" {
  datastore          = "local-ssd-01"
  source_file        = "/Users/johnsonryan/Downloads/file.vmdk"
  destination_file   = "gh-1612/file.vmdk"
  create_directories = true
  datacenter         = data.vsphere_datacenter.datacenter.name
}
```

The error shown in the [previous comment](https://github.com/hashicorp/terraform-provider-vsphere/issues/1587#issuecomment-1060603749) **_only manifests when_** the directory does not exist and I do not include the `create_directories` argument.

> re: 2 conditions here need to be analyzed
> 
> 1. when destination directory doesn't exist , create the directory and copy the file .
> 2. when destination directory exists just copy the file to the destination

1.  ✅ Works with `create_directories = true`. Uploaded to tmp path, directory created, vmdk moved to final directory and tmp deleted.
2.  ✅ Works with `create_directories = true`. Uploaded to tmp path, directory created, vmdk moved to final directory and tmp deleted. 

If the directory already exists, the following can also be used without `create_directories = true`:

```hcl
resource "vsphere_file" "gh-1614" {
  datastore          = "local-ssd-01"
  source_file        = "/Users/johnsonryan/Downloads/file.vmdk"
  destination_file   = "gh-1612/file.vmdk"
  datacenter         = data.vsphere_datacenter.datacenter.name
}
```

❓ Can you help clarify if I am misunderstanding the scenario or test case?

Ryan

**Comment by Kishanbhatk** [comment] 2022-03-12 04:47
Hi , we doesnt want to use the create_directories option , since create_directories option will throw the error if the destination directory is already existing

**Comment by Kishanbhatk** [comment] 2022-03-12 04:49
Suppose if the directory is already existing and if you use the 'create_directories' option it will throw the error right ?

**Comment by Kishanbhatk** [comment] 2022-03-12 04:58
Will try out with create_directories option and let you know the output which I am getting

**Comment by Kishanbhatk** [comment] 2022-03-12 05:21
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "2.1.0"
    }
  }
}

provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore_name
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = "cluster1/Resources"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_file" "upload" {
  for_each = var.images

  datacenter = data.vsphere_datacenter.datacenter.id
  datastore  = var.vsphere_datastore_name
  create_directories = true
  source_file        = each.value
  destination_file   = "source_files/${basename(each.value)}"
}
// Here the 'source_files' directory is already existing and I am using create_directories option as you had specified  in point 2 of first case ✅ successfully upload a VMDK fine when the directory does exist already without any issues.
The error I am getting ,

terraform apply --auto-approve
data.vsphere_datacenter.datacenter: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
vsphere_file.upload["vmdk1"]: Creating...

Error: error ServerFaultCode: Cannot complete the operation because the file or folder [datastore1] source_files already exists

  on main.tf line 32, in resource "vsphere_file" "upload":
  32: resource "vsphere_file" "upload" {

**Comment by Kishanbhatk** [comment] 2022-03-12 05:25
The dierctory needs to be created only if doesnt exists , just try out the ISO upload without 'create_directories' option for 2 cases 
1) Destination directory doesnt exist and you are uploading 
2) Destination directory is existing and you are uploading 

On both the cases ISO is uploaded but VMDK doesnt produce this behaviour

**Comment by Kishanbhatk** [comment] 2022-03-12 05:30
Since 'create_directories' option will throw the error saying **folder is already existing** , we are not using that option , we need flexibility in directory creation in data store without any issues for our production

**Comment by tenthirtyam** [comment] 2022-03-12 07:13
Thanks for the updates. Unfortunately, in my environment I’m e not yet been able to reproduce the same results. I’ll do some more testing late next week to see if so can reproduce the same error.

**Comment by tenthirtyam** [comment] 2022-03-12 07:50
One interesting point, your plan should not work with the following:

`datacenter = data.vsphere_datacenter.datacenter.id`

It should be:

`datacenter = data.vsphere_datacenter.datacenter.name`

Ryan

**Comment by Kishanbhatk** [comment] 2022-03-12 07:59
Hmm , Yeah I got your point , Maybe I can change it and try out once is that Okay ?

**Comment by Kishanbhatk** [comment] 2022-03-12 08:02
I got to observe this now , surprisingly even though we pass the id for **datacenter** instead of name it was was passing the plan phase , is that a bug ?

**Comment by Kishanbhatk** [comment] 2022-03-12 08:22
> One interesting point, your plan should not work with the following:
> 
> `datacenter = data.vsphere_datacenter.datacenter.id`
> 
> It should be:
> 
> `datacenter = data.vsphere_datacenter.datacenter.name`
> 
> Ryan

This is the plan for the main.tf which I had previously added.
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vsphere_datacenter.datacenter: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_file.upload["vmdk1"] will be created
  + resource "vsphere_file" "upload" {
      + create_directories = true
      + datacenter         = "ha-datacenter"
      + datastore          = "datastore1"
      + destination_file   = "source_files/file.vmdk"
      + id                 = (known after apply)
      + source_file        = "/home/kishan/images/file.vmdk"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

2) One more thing what I had observed is , we dont have attribute reference such as **'name'** for the data source **vsphere_datacenter** ,
Reference :  https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/data-sources/datacenter

**Comment by Kishanbhatk** [comment] 2022-03-12 08:32
This is the plan when I use **data.vsphere_datacenter.datacenter.name** instead of **data.vsphere_datacenter.datacenter.id**,

terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vsphere_datacenter.datacenter: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  vsphere_file.upload["vmdk1"] will be created
  + resource "vsphere_file" "upload" {
      + create_directories = true
      + datastore          = "datastore1"
      + destination_file   = "source_files/file.vmdk"
      + id                 = (known after apply)
      + source_file        = "/home/kishan/images/file.vmdk"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------
By observing the 2 plans when we use id its taking the **datacenter** value and in the below plan **datacenter** value is not being taken care for upload

**Comment by tenthirtyam** [comment] 2022-03-15 20:36
I'm attaching a demo video with v2.1.1 using your example configuration with slight modification.

Here are the plan files:
[gh-1587_plan.zip](https://github.com/hashicorp/terraform-provider-vsphere/files/8256862/gh-1587_plan.zip)

And here is a demo that shows the use of the same plan.

https://user-images.githubusercontent.com/7771363/158466475-fae0e2fd-b393-4463-8eb6-44ba02e177d4.mp4

- Notice that at the time the first `terraform apply` is run it creates the directories (`source_files`) if needed and it is successful.
- The `terraform destroy` removes the files but leaves the `source_files` directory, as expected. 
- So, on the next `terraform apply`, the .vmdks are uploaded to the existing directory w/o issue or error even with `create_directories` flagged as `true`.

Notice that I am using `datacenter = data.vsphere_datacenter.datacenter.name` in the resource to target the **name** of the datacenter.

Ryan

**Comment by Kishanbhatk** [comment] 2022-03-16 05:47
Hi , which version of the terraform that you use ?

**Comment by Kishanbhatk** [comment] 2022-03-16 06:23
Will check this out get back to you

**Comment by tenthirtyam** [comment] 2022-03-16 06:56
Tested with latest v1.1.7.

**Comment by Kishanbhatk** [comment] 2022-03-16 07:10
Hi , you are using Vsphere client ? I am using the VMware Esxi , I tried your code too , getting the same error

**Comment by Kishanbhatk** [comment] 2022-03-16 07:14
This is the ESXI version I am using and I am not using the Vsphere client ,

VMware ESXi™
Copyright © 1998-2021 VMware, Inc. All rights reserved. This product is protected by U.S. and international copyright and intellectual property laws. VMware products are covered by one or more patents listed at http://www.vmware.com/go/patents.

Client version:
X.X.X.X

Client build number:
X.X.X.X.X

ESXi version:
7.0.2

**Comment by tenthirtyam** [comment] 2022-03-16 12:30
Are yo

**Comment by tenthirtyam** [comment] 2022-03-16 12:31
Are you using an unmanaged ESXi host with the free version of the vSphere Hypervisor?

**Comment by Kishanbhatk** [comment] 2022-03-16 12:59
Yeah ,

Its not managed by any vcenter server ,

Version:
7.0 Update 2

State:
Normal (not connected to any vCenter Server)

Uptime:
28.24 days

**Comment by Kishanbhatk** [comment] 2022-03-16 13:00
Regarding the features , It is running in evaluation mode and not free licensing is used

**Comment by tenthirtyam** [comment] 2022-03-16 13:03
This does explain the datacenter argument matter. Because it’s not managed by a vCenter Server instance there would be no datacenter name available.

**Comment by Kishanbhatk** [comment] 2022-03-16 13:19
Yeah its there as a note it will be ignored and will take the default datacenter value 

When used against ESXi, this data source always fetches the server's "default" datacenter, which is a special datacenter unrelated to the datacenters that exist in any vCenter server that might be managing this host. Hence, the name attribute is completely ignored.

**Comment by tenthirtyam** [comment] 2022-03-16 13:20
I can confirm that I can recreate the issue when using a direct ESXi host connection - this was an important detail left out of the issue description. 

I can also confirm that when using a direct ESXi host connection that the datacenter id is required since the name would not be resolvable if Terraform nor the host are connected to a vCenter Server instance.

I'll take a look at the proposed fix but will need to determine if this is something the provider team wishes to address.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by Kishanbhatk** [comment] 2022-03-16 13:21
Sorry @tenthirtyam its my fault I had missed out this point earlier . Thank you for all your follow up regarding this issue till now

**Comment by tenthirtyam** [comment] 2022-03-16 17:20
Hi Kishan,

After review of the implementation for the `r/vsphere_file` resource, some additional testing of the issue and the proposed modification, and the general intent for the provider to primarily interface with vCenter Server for vSphere operations here's a high-level overview of the situation...

As of v2.1.0. the provider can connect to the vCenter Server, upload a number of `.vmdk+` files using `r/vsphere_file`. Those `vmdk` files are uploaded to a temporary directory after which the virtual disks are moved and inflated at the final destination within the vSphere datacenter name. If the directories need to be created, the `create_directories = true` will assist with the process, as required. During the move of the virtual disk to the final destination, the temporary directories are removed as expected.

> Note: The functionality had been added prior but was not 100% for `.vmdk` until the v2.1.0 release.

However, if the target is either managed or unmanaged ESXi host (_instead of a vCenter Server endpoint_) the configuration and behavior would be different:
- The datacenter must be changed to `.id` vs `.name` (or set to the host default of `ha-datacenter`); which is a change to the use of the resource and the documentation.
- The proposed change would address creating the directories, but the use of `create_directories` would conflict; which is a change to the use of the resource and the documentation.
- The proposed change would address uploading and moving the `.vmdk` files, but the temporary directories would still be present; which would be a poor experience.

Based on these factors, the intent for the provider to primarily interface with vCenter Server for vSphere operations this issue will be closed. _However_, I will open and link an enhancement request to track community reactions and discussions on the topic to help warrant enhancements to the implementation to support direct ESXi host endpoints alongside vCenter Server endpoints with the same user experience, keeping in mind any breaking changes between versions.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Closed** 2022-03-16 17:21 UTC
Labels: bug, declined, acknowledged, area/storage

**Comment by tenthirtyam** [comment] 2022-03-16 17:43
Enhancement issue https://github.com/hashicorp/terraform-provider-vsphere/issues/1623 has been submitted for community reactions.
