### ISSUE TITLE
Add support for domain_OU windows customization

### ISSUE THREAD

**Issue by ultral** [hashicorp/terraform-provider-vsphere#2180] opened 2024-04-26 10:03 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

there is realted https://github.com/hashicorp/terraform-provider-vsphere/issues/996 . however after that domain_OU parameter has been released in vcenter 8.

### Use Case(s)

add VM into specific during creation via single param i.e.
```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ...
  clone {
    # ... other configuration ...
    customize {
      # ... other configuration ...
      windows_options {
        domain_ou             = "OU=Sandbox,OU=Workstations,DC=example,DC=com"
      }
    }
  }
}
```
instead kludges like

```hcl
  provisioner "remote-exec" {
   inline = [
     "powershell.exe Add-Computer -DomainName 'example.com' -OUPath 'OU=Sandbox,OU=Workstations,DC=example,DC=com' -Credential (New-Object System.Management.Automation.PSCredential('example\\DomainJoin', (ConvertTo-SecureString 'mysecretpassword' -AsPlainText -Force))) -Restart -Force"
   ]
    connection {
     type     = "winrm"
     user     = "Administrator"
     password = "anothersecretpassword"
     use_ntlm = true
     host     = self.default_ip_address
    }
  }

  provisioner "remote-exec" {
   when = destroy
   inline = [
     "powershell.exe Remove-Computer -UnjoinDomaincredential (New-Object System.Management.Automation.PSCredential('example\\DomainJoin', (ConvertTo-SecureString 'mysecretpassword' -AsPlainText -Force))) -Force"
   ]
   connection {
     type     = "winrm"
     user     = "DomainJoin"
     password = "mysecretpassword"
     use_ntlm = true
     host     = self.default_ip_address 
    }
  }
} 
```

### Potential Terraform Provider Configuration

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ...
  clone {
    # ... other configuration ...
    customize {
      # ... other configuration ...
      windows_options {
        domain_ou             = "OU=Sandbox,OU=Workstations,DC=example,DC=com"
      }
    }
  }
}
```

### References

* https://github.com/hashicorp/terraform-provider-vsphere/issues/996
* https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/data-structures/Guest/Domain/
* https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-unattendedjoin-identification-machineobjectou

**Comment by tenthirtyam** [comment] 2024-04-26 12:48
Duplicate of #2130

**Closed** 2024-04-26 12:49 UTC
Labels: duplicate, enhancement
