### ISSUE TITLE
Datastore:<computed>' has already been deleted or has not been completely create

### ISSUE THREAD

**Issue by saintsinnerr** [hashicorp/terraform-provider-vsphere#2040] opened 2023-10-13 08:57 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.5.3

### Terraform Provider

v2.4

### VMware vSphere

v.8.0.2.00000

### Description

Hi, I’m using terraform to create virtual machines with hashicorp/vsphere"
So far, there have been no problems creating them for a long time, but now when I try and do everything the same way, the following error appears:
Error: disk.0: ServerFaultCode: The object ‘vim.Datastore:’ has already been deleted or has not been completely created
I tried manually setting #datastore_id = “datastore -2236” and it worked, but that doesn’t solve my problem.

### Affected Resources or Data Sources

vsphere_virtual_machine

### Terraform Configuration

```
locals {
  # disk_index = compact(distinct(flatten([for disk in var.virtual_machines : [try(disk.disk1, null), try(disk.disk2, null), try(disk.disk3, null), try(disk.disk4, null)]])))
  disk_map = try(merge(flatten([for key in var.virtual_machines : key.disks])...), var.virtual_machines_disks)
}

data "vsphere_datacenter" "datacenter" {
  name = var.datacenter
}

data "vsphere_network" "network" {

  for_each = var.virtual_machines

  name          = each.value["network"]
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore_cluster" "datastore_cluster" {
  name          = var.datastore_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}


data "vsphere_virtual_machine" "template" {
  name          = var.common_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {

  for_each = var.virtual_machines

  name                  = each.value["name"]
  resource_pool_id      = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_cluster_id  = data.vsphere_datastore_cluster.datastore_cluster.id
  num_cpus              = try(each.value["cpu"], "1")
  num_cores_per_socket  = try(each.value["cores"], data.vsphere_virtual_machine.template.num_cores_per_socket)
  memory                = each.value["memory"] * 1024
  memory_reservation    = can(each.value["memory_reservation"]) ? each.value["memory"] : null
  guest_id              = data.vsphere_virtual_machine.template.guest_id
  scsi_type             = data.vsphere_virtual_machine.template.scsi_type
  scsi_controller_count = 4 # count the disks + 1 disk0 is not part of virtual_machines_disks
  network_interface {
    network_id   = data.vsphere_network.network[each.key].id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }
  disk {
    label           = "disk0"
    controller_type = "scsi"
    size            = each.value["disk"]
    # size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
    unit_number      = 0
```

### Debug Output

https://gist.github.com/saintsinnerr/714483b4e3e2ac50d61b7af860499687

### Expected Behavior

create VM

### Actual Behavior

│ Error: disk.0: ServerFaultCode: The object 'vim.Datastore:<computed>' has already been deleted or has not been completely created

### Steps to Reproduce

terraform init
terraform plan
terraform apply

**Comment by vasilsatanasov** [comment] 2023-10-16 07:01
@saintsinnerr you are probably using the 2.5 release of the provider since the issue that you are describing is a regression introduced in 2.5 and fixed in 2.5.1 with this one https://github.com/hashicorp/terraform-provider-vsphere/issues/2034. Can you confirm the symptoms and that upgrading to 2.5.1 fixes your case ?

**Comment by vasilsatanasov** [comment] 2023-10-16 07:03
Duplicate of #2034

**Closed by vasilsatanasov** 2023-10-16 07:03 UTC
Labels: bug, needs-triage

**Comment by saintsinnerr** [comment] 2023-10-16 08:52
I changed the version to 2.5.1 and that solved the problem.Thanks a lot !
