### ISSUE TITLE
Creating a `r/virtual_machine` requires `VirtualMachine.Config.SwapPlacement` privilege 

### ISSUE THREAD

**Issue by mikequentel** [hashicorp/terraform-provider-vsphere#1212] opened 2020-09-15 22:05 UTC
### Terraform Version
`v0.13.1`
### vSphere Provider Version
`v1.24.0`

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

**providers.tf**

```
provider "vsphere" {
  version              = "1.24.0"
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}
```

**main.tf**
```
data "vsphere_datacenter" "dc" {
  name = var.datacenter_name
}

data "vsphere_host" "host" {
  name          = var.vsphere_host
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = var.pool_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.network_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  name             = var.vm_name
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  host_system_id   = data.vsphere_host.host.id

  num_cpus = var.vm_cpu_number
  memory   = var.vm_memory
  guest_id = var.vm_guest_id

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label        = var.vm_disk_label
    size         = var.vm_disk_size
    datastore_id = data.vsphere_datastore.datastore.id
  }

  cdrom {
    datastore_id = data.vsphere_datastore.datastore.id
    path         = var.vm_cd
  }

  network_interface {
    network_id = data.vsphere_network.network.id
  }

}
```

**Plan**
```
  # vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "datastore-35377"
      + default_ip_address                      = (known after apply)
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "bios"
      + force_power_off                         = true
      + guest_id                                = "ubuntu64guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = "host-9365"
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 1024
      + memory_limit                            = -1
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "devops-example-tf"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 1
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-8807"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + cdrom {
          + datastore_id   = "datastore-35377"
          + device_address = (known after apply)
          + key            = (known after apply)
          + path           = "iso_images/ubuntu-20.04.1-live-server-amd64.iso"
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "datastore-35377"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "disk0"
          + path              = (known after apply)
          + size              = 20
          + storage_policy_id = (known after apply)
          + thin_provisioned  = true
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-19"
        }
      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-19"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

### Expected Behavior

Expected to be able to generate a simple VM, just like I successfully did using **`govc`**

### Actual Behavior

**Error**
```
2020/09/15 17:42:42 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate.d/dev/terraform.tfstate using fcntl flock
Error: error creating virtual machine: ServerFaultCode: Permission to perform this operation was denied.

  on main.tf line 25, in resource "vsphere_virtual_machine" "vm":
  25: resource "vsphere_virtual_machine" "vm" {
```
```
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault>
<faultcode>ServerFaultCode</faultcode>
<faultstring>Permission to perform this operation was denied.</faultstring>
<detail>
<NoPermissionFault xmlns="urn:vim25" xsi:type="NoPermission">
<object type="Folder">group-v3</object>
<privilegeId>VirtualMachine.Config.SwapPlacement</privilegeId>
</NoPermissionFault>
</detail>
</soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>
```

### Steps to Reproduce
```
terraform init
terraform workspace select dev || terraform workspace new dev
terraform apply
```

### Important Factoids
Can remotely create the VM using `govc`, so why would permissions for Terraform not work?
For example, this successfully creates a VM:
```
govc vm.create -disk=20GB -ds=ESX_Engineering_Datastore_01 -g=ubuntu64guest -iso=iso_images/ubuntu-20.04.1-live-server-amd64.iso -on=true -link=false -net="VM Network" -host="vmware14.mycompany.com" devops-example-govc
```
Also, the vSphere custom user (*Terraform Users*) has the permission **Swapfile placement** set--not trying to run this as a vSphere Administrator (nor should one have to, in my opinion). The successful `govc vm.create` was run using the exact same user account (*Terraform Users*).

### References

* https://stackoverflow.com/questions/63902881/can-remotely-create-a-vm-using-govc-but-not-with-terraform

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by djalai** [comment] 2020-10-12 14:46
Hi,


+1 to this one. 
The default behaviour should be to omit this parameter instead of enforcing a default value.
I think in most case unprivileged users are not given that permission on vsphere as it is really sensitive.

**Comment by tenthirtyam** [comment] 2022-01-25 22:40
Hi @mikequentel, I suspect that the issue is related to the following:

https://github.com/hashicorp/terraform-provider-vsphere/blob/04f9ec0827e12f3e1089e2ba6daa056c0fd62fb0/vsphere/virtual_machine_config_structure.go#L242-L248

Even though the argument is optional and would default to inheritance using the UI, API, PowerCLI, govc, etc, by virtue of the provider **_setting_** the `Default` ...

```go
Default: string(types.VirtualMachineConfigInfoSwapPlacementTypeInherit), 
```

... I suspect that this is the cause for the provider requiring the `VirtualMachine.Config.SwapPlacement` privilege unnecessarily.

cc @appilon for review/comment on if this might be easily resolvable by removing setting the `Default` value.

**Ryan Johnson** 
Staff II Solutions Architect, VMware, Inc.
[credly.com/users/tenthirtyam](credly.com/users/tenthirtyam)

**Comment by appilon** [comment] 2022-01-28 21:13
If we can remove the default (allowing empty string to be the default) then it should not be a breaking change for anyone. If the default has to change, then I believe it will be a breaking change.

**Comment by tenthirtyam** [comment] 2022-01-28 21:16
I'll self-assign this issue to research/test.

**Comment by tenthirtyam** [comment] 2022-02-01 02:51
Hey @appilon, after a little investigation, this issue **seems** to be much further down than simply removing this default mentioned above. There's the logic for both the virtual machine resource and virtual disk subresource to query the status of storage policy-based management (`spbm`), compute the storage policy, and so forth. 

Let's discuss how it might be addressed or if it's a nuance based on the provider implementation.

**Comment by tenthirtyam** [comment] 2022-03-11 21:37
Hi @mikequentel,

A could quick questions:
- Which version of vSphere is in use in the environemnt?
- Can you see if this  is reproducible with the [latest](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest) version of the provider?
- Can you share the specific list of privileges you've assigned to the role for repoduction?

I tested with the following this afternoon and it does not return the error unless I select non-default  `vmDirectory` or `hostLocal`.

- Terraform v1.1.7
- Terraform Provider for VMware vSphere v2.1.1
- VMware vSphere 7.0.3(c)

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ....
  swap_placement_policy   = "inherit"
  # ... the above is the default, but setting explicitly....
}
```

My user, `terraform@rainpole.io`, does not have the Change Swap Placement (`VirtualMachine.Config.SwapPlacement`) privilege enabled. 

- On the first apply, It deploys with the default `inherit` w/o issue. 
- The second and third apply try the non-defaults and return the expected error.
- On the fourth apply its set back to the default and completed with no changes.

```console
❯ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + annotation                              = (known after apply)
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "datastore-11"
      + default_ip_address                      = (known after apply)
      + efi_secure_boot_enabled                 = true
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "efi"
      + folder                                  = "workloads"
      + force_power_off                         = true
      + guest_id                                = "centos8_64Guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = (known after apply)
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 4096
      + memory_limit                            = -1
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "centos-test"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 2
      + power_state                             = (known after apply)
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-6046"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + tools_upgrade_policy                    = "manual"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + template_uuid = "42023ec5-63c7-8821-2ec9-a07c734718ba"
          + timeout       = 30

          + customize {
              + dns_server_list = [
                  + "172.16.11.11",
                  + "172.16.11.12",
                ]
              + dns_suffix_list = [
                  + "rainpole.io",
                ]
              + ipv4_gateway    = "172.16.11.1"
              + timeout         = 10

              + linux_options {
                  + domain       = "rainpole.io"
                  + host_name    = "centos-test"
                  + hw_clock_utc = true
                  + script_text  = <<-EOT
                        #!/bin/sh
                        if [ x$1=x"precustomization" ];
                        then
                          mkdir -p /i-am/precustomization
                        fi
                        if [ x$1=x"postcustomization" ];
                        then
                          mkdir -p /i-am/postcustomization
                        fi
                    EOT
                }

              + network_interface {
                  + ipv4_address = "172.16.11.111"
                  + ipv4_netmask = 24
                }
            }
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "<computed>"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "disk0"
          + path              = (known after apply)
          + size              = 40
          + storage_policy_id = (known after apply)
          + thin_provisioned  = false
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-1001"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
vsphere_virtual_machine.vm: Still creating... [30s elapsed]
vsphere_virtual_machine.vm: Still creating... [40s elapsed]
vsphere_virtual_machine.vm: Still creating... [50s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m40s elapsed]
vsphere_virtual_machine.vm: Creation complete after 2m47s [id=42020036-a94c-6328-25ae-42b34253ff07]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
❯ terraform apply -auto-approve
vsphere_virtual_machine.vm: Refreshing state... [id=42020036-a94c-6328-25ae-42b34253ff07]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # vsphere_virtual_machine.vm has changed
  ~ resource "vsphere_virtual_machine" "vm" {
      + custom_attributes                       = {}
      + extra_config                            = {}
        id                                      = "42020036-a94c-6328-25ae-42b34253ff07"
        name                                    = "centos-test"
      + pci_device_id                           = []
      + tags                                    = []
        # (66 unchanged attributes hidden)

      ~ clone {
          + ovf_network_map = {}
          + ovf_storage_map = {}
            # (3 unchanged attributes hidden)

          ~ customize {
                # (4 unchanged attributes hidden)


              ~ network_interface {
                  + dns_server_list = []
                    # (3 unchanged attributes hidden)
                }
                # (1 unchanged block hidden)
            }
        }


        # (2 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using
ignore_changes, the following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
        id                                      = "42020036-a94c-6328-25ae-42b34253ff07"
        name                                    = "centos-test"
      ~ swap_placement_policy                   = "inherit" -> "hostLocal"
        tags                                    = []
        # (68 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
vsphere_virtual_machine.vm: Modifying... [id=42020036-a94c-6328-25ae-42b34253ff07]
╷
│ Error: ServerFaultCode: Permission to perform this operation was denied.
│ 
│   with vsphere_virtual_machine.vm,
│   on main.tf line 37, in resource "vsphere_virtual_machine" "vm":
│   37: resource "vsphere_virtual_machine" "vm" {
│ 
╵
❯ terraform apply -auto-approve
vsphere_virtual_machine.vm: Refreshing state... [id=42020036-a94c-6328-25ae-42b34253ff07]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # vsphere_virtual_machine.vm has changed
  ~ resource "vsphere_virtual_machine" "vm" {
      ~ guest_ip_addresses                      = [
          - "172.16.11.111",
          - "fe80::250:56ff:fe82:eef9",
        ]
        id                                      = "42020036-a94c-6328-25ae-42b34253ff07"
        name                                    = "centos-test"
      ~ power_state                             = "on" -> "off"
        tags                                    = []
      ~ vmware_tools_status                     = "guestToolsRunning" -> "guestToolsNotRunning"
        # (66 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using
ignore_changes, the following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
        id                                      = "42020036-a94c-6328-25ae-42b34253ff07"
        name                                    = "centos-test"
      ~ swap_placement_policy                   = "inherit" -> "vmDirectory"
        tags                                    = []
        # (68 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
vsphere_virtual_machine.vm: Modifying... [id=42020036-a94c-6328-25ae-42b34253ff07]
╷
│ Error: ServerFaultCode: Permission to perform this operation was denied.
│ 
│   with vsphere_virtual_machine.vm,
│   on main.tf line 37, in resource "vsphere_virtual_machine" "vm":
│   37: resource "vsphere_virtual_machine" "vm" {
│ 
╵
❯ terraform apply -auto-approve
vsphere_virtual_machine.vm: Refreshing state... [id=42020036-a94c-6328-25ae-42b34253ff07]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so
no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
[credly.com/users/tenthirtyam](https://github.com/hashicorp/terraform-provider-vsphere/issues/credly.com/users/tenthirtyam)

**Comment by tenthirtyam** [comment] 2022-03-17 17:29
Hi @mikequentel,

A quick follow-up:

- Which version of vSphere is in use in the environment?
- Can you see if this is reproducible with the [latest](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest) version of the provider?
- Can you share the specific list of privileges you've assigned to the role for repoduction?

I tested with the following this afternoon and it does not return the error unless I select non-default  `vmDirectory` or `hostLocal`.

- Terraform v1.1.7
- Terraform Provider for VMware vSphere v2.1.1
- VMware vSphere 7.0.3(c)

```hcl
resource "vsphere_virtual_machine" "vm" {
  # ... other configuration ....
  swap_placement_policy   = "inherit"
  # ... the above is the default, but setting explicitly....
}
```

My user, `terraform@rainpole.io`, does not have the Change Swap Placement (`VirtualMachine.Config.SwapPlacement`) privilege enabled. 

- On the first apply, It deploys with the default `inherit` w/o issue. 
- The second and third apply try the non-defaults and return the expected error.
- On the fourth apply its set back to the default and completed with no changes.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-03-28 16:03
Hi @mikequentel 👋 - a gentle reminder regarding the [prior inquiry](https://github.com/hashicorp/terraform-provider-vsphere/issues/1212#issuecomment-1071125767).

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Closed** 2022-06-15 20:56 UTC
Labels: bug, documentation, acknowledged, area/storage, area/iam
