### ISSUE TITLE
Terraform Vsphere remove disk on datastore after terraform destroy

### ISSUE THREAD

**Issue by jbrunetext** [hashicorp/terraform-provider-vsphere#1466] opened 2021-08-12 21:04 UTC
### Description
Terraform Vsphere remove disk on datastore after terraform destroy

### Potential Terraform Configuration

it would be nice to implement this feature when you wamt to destroy a vm , you also need to remove vmx file on datastore

**Comment by tenthirtyam** [comment] 2021-11-05 00:10
@jbrunetext - I've not experienced this particular issue with a destroy operation on `vsphere_virtual_machine` resources. Can you elaborate on this issue by copying the below and updating the contents of the original issue summary?

- [ ] Terraform version

- [ ] Terraform provider for vSphere version:

- [ ] vSphere version:

- [ ] Affected Resource(s): 
       - e.g. `vsphere_virtual_machine`

- [ ] Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

- [ ] Debug Output

```bash
```

- [ ]  Panic Output, if applicable.

```bash
```

- [ ] Expected Behavior

- [ ] Actual Behavior

- [ ] Steps to Reproduce

- [ ] Important Factoids

- [ ] References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Ryan
@tenthirtyam

**Comment by tenthirtyam** [comment] 2021-11-05 00:10
Recommend: `type/bug` as this is not `type/enhancement`

**Comment by tenthirtyam** [comment] 2022-01-17 18:43
cc @iBrandyJackson for review.

**Comment by tenthirtyam** [comment] 2022-01-27 02:22
Hi @jbrunetext ,

Below is a real-time demo I recorded with the virtual machine configuration files and disk0 files on a single datastore in the same directory. When the virtual machine is destroyed, all files and the containing directory are appropriately removed.

![gh-1466](https://user-images.githubusercontent.com/7771363/151279852-41f86323-d8e2-4e78-b10c-f692b0a82ca3.gif)

For reference, below are the file constructs for this basic example Terraform plan.

`versions.tf`

```hcl
##################################################################################
# VERSIONS
##################################################################################

terraform {
  required_providers {
    vsphere = {
      source  = "local/vmware/vsphere"
      version = ">= 2.0.3"
    }
  }
  required_version = ">= 1.1.4"
}
```

`varaibles.tf`

```hcl
##################################################################################
# VARIABLES
##################################################################################

# Credentials

variable "vsphere_server" {
  type = string
}

variable "vsphere_username" {
  type = string
}

variable "vsphere_password" {
  type = string
}

variable "vsphere_insecure" {
  type    = bool
  default = false
}

# vSphere Settings

variable "vsphere_datacenter" {
  type = string
}

variable "vsphere_cluster" {
  type = string
}

variable "vsphere_datastore" {
  type = string
}

variable "vsphere_folder" {
  type = string
}

variable "vsphere_network" {
  type = string
}

variable "vsphere_template" {
  type = string
}

# Virtual Machine Settings

variable "vm_name" {
  type = string
}

variable "vm_cpus" {
  type = number
}

variable "vm_memory" {
  type = number
}

variable "vm_firmware" {
  type = string
}

variable "vm_efi_secure_boot_enabled" {
  type = bool
}

variable "vm_hostname" {
  type = string
}

variable "vm_domain" {
  type = string
}

variable "vm_ipv4_address" {
  type = string
}

variable "vm_ipv4_netmask" {
  type = string
}

variable "vm_ipv4_gateway" {
  type = string
}

variable "vm_dns_suffix_list" {
  type = list(string)
}

variable "vm_dns_server_list" {
  type = list(string)
}

variable "domain" {
  type = string
}

variable "domain_admin_username" {
  type = string
}

variable "domain_admin_password" {
  type = string
}

variable "vm_admin_password" {
  type = string
}
```

`main.tf`
```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = format("%s%s", data.vsphere_compute_cluster.cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  sync_time_with_host = false
  folder                  = var.vsphere_folder
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  guest_id                = data.vsphere_virtual_machine.template.guest_id
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
    datastore_id     = data.vsphere_datastore.datastore.id
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
      windows_options {
        computer_name         = var.vm_name
        join_domain           = var.domain
        domain_admin_user     = var.domain_admin_username
        domain_admin_password = var.domain_admin_password
        admin_password        = var.vm_admin_password
      }
      network_interface {
        ipv4_address = var.vm_ipv4_address
        ipv4_netmask = var.vm_ipv4_netmask
      } 

      ipv4_gateway    = var.vm_ipv4_gateway
      dns_suffix_list = var.vm_dns_suffix_list
      dns_server_list = var.vm_dns_server_list
    }
  }

  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
}
```

`terraform.tfvars`

```hcl
##################################################################################
# VARIABLES
##################################################################################

# Credentials

vsphere_server   = "m01-vc01.rainpole.io"
vsphere_username = "administrator@vsphere.local"
vsphere_password = "VMware1!"
vsphere_insecure = true

# vSphere Settings

vsphere_datacenter = "m01-dc01"
vsphere_cluster    = "m01-cl01"
vsphere_datastore  = "local-ssd-02"
vsphere_folder     = ""
vsphere_network    = "M - 172.16.11.0"
vsphere_template   = "windows-server-2016-standard-dexp-v22.01"

# Virtual Machines Settings

vm_name                    = "windows-test"
vm_cpus                    = 2
vm_memory                  = 4096
vm_firmware                = "efi"
vm_efi_secure_boot_enabled = true
vm_hostname                = "windows-test"
vm_domain                  = "rainpole.io"
vm_ipv4_address            = "172.16.11.123"
vm_ipv4_netmask            = "24"
vm_ipv4_gateway            = "172.16.11.1"
vm_dns_suffix_list         = ["rainpole.io"]
vm_dns_server_list         = ["172.16.11.11", "172.16.11.12"]
domain                     = "rainpole.io"
domain_admin_username      = "administrator@rainpole.io"
domain_admin_password      = "VMware1!"
vm_admin_password          = "VMware1!"
```

cc @iBrandyJackson and @appilon for review.

**Comment by appilon** [comment] 2022-01-27 19:31
I am going to close the issue due to lack of context on the original post and time since last response, please feel free to open a new issue if needed.

**Closed by appilon** 2022-01-27 19:31 UTC
Labels: enhancement
