### ISSUE TITLE
Unable to enumerate all disks error when building Oracle Linux 8 VM

### ISSUE THREAD

**Issue by 8uachaille** [hashicorp/terraform-provider-vsphere#1639] opened 2022-03-29 16:44 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.7

### Terraform Provider

v2.1.1

### VMware vSphere

v6.7 18828794 

### Description

I am trying to build my first Oracle Linux 8.5 VM but my build is failing with following error in vSphere.

Task name.    Power On virtual machine
Target.           oel-8-test2.{domain redacted}
Status.           Unable to enumerate all disks.  The file specified is not a virtual disk.

This failure does not happen when I build the VM with a single disk, it only happens when I build the VM with >1 disks.

Equivalent manifests with multiple disks are working ok for building CentOS 7 using Terraform 0.12.20 when I force Provider < 1.16.  I tried those versions first (I know they are old) for Oracle Linux 8 and those didn't work with the same errors, so I installed the latest terraform binary in a temporary dir.

Oracle Linux 8 installs manually with Firmware set to EFI so I added the following to my Terraform manifest 

  firmware = "efi"

I unset the forcing of Provider to < 1.16 in my manifest.

In order to get Provider 2.1.1 to work, I added the Storage Profile View privilege to the custom role I use for Terraform in vSphere.  I was previously advised that this was required post v1.15.

I read https://github.com/hashicorp/terraform-provider-vsphere/issues/1578 which looked promising so I added the following to my manifest too - 

  efi_secure_boot_enabled = true

But .. the issue persisted.

It seems that the 2nd disk is created at some level of the VM configuration because I see Hard Disk 1 and Hard Disk 2 in the vSphere GUI.  The 2nd disk is correctly addressed SCSI(0:1) although this address does not appear in the Terraform TRACE log.  Note my template only has 1 disk, so Terraform is creating this 2nd disk.  

The size of the second disk is 0 when it should be 100GB.  Also, the disk file for the 2nd disk is set to the datastore name rather than the expected vmdk file.  

I checked the hypervisor dir containing the VM data/config and there is only one vmdk as follows - 

```
[root@{redacted}:/vmfs/volumes/{redacted}/oel-8-test2{redacted}] ls -lrt
total 62856192
-rw-------    1 root     root     53687091200 Mar 29 14:47 oel-8-test2{redacted}_2-flat.vmdk. <----
-rw-------    1 root     root           543 Mar 29 14:47 oel-8-test2{redacted}_2.vmdk
-rw-------    1 root     root        270840 Mar 29 14:47 oel-8-test2{redacted}.nvram
-rw-r--r--    1 root     root             0 Mar 29 14:50 oel-8-test2{redacted}.vmsd
-rw-------    1 root     root     10675552256 Mar 29 14:50 _deviceImage-0.iso
-rw-r--r--    1 root     root           604 Mar 29 14:50 oel-8-test2{redacted}-6a996044.hlog
-rw-------    1 root     root        545061 Mar 29 14:50 imcf-07cT7s
-rwxr-xr-x    1 root     root          3390 Mar 29 14:51 oel-8-test2{redacted}.vmx
[root@{redacted}:/vmfs/volumes/{redacted}c/oel-8-test2{redacted}]
```

I noticed the rogue  _deviceImage-0.iso (The original ISO) in there so I removed the CD-ROM device which called that from the template, rebuilt and the issue persisted.  I then added a vanilla CD-ROM device to the template, rebuilt yet again and the issue persisted.

When I comment out the following, which is identical syntax & content (except for the label, size and unit_number) to logical unit_number 0, the VM build works ok

```
  // {redacted} filesystem
   disk {
    label            = "disk1"
    thin_provisioned = "false"
    eagerly_scrub    = "true"
    size             = 100
    unit_number      = 1
   }
```
   
Lastly, I tried setting the above unit_number to 2 instead but the same error was produced.

I am out of ideas and hoping that someone can help.

### Affected Resources

Virtual Machine.

### Terraform Configuration

https://gist.github.com/8uachaille/7b3aae16868537388eecfb963386f11f

### Debug Output

https://gist.github.com/8uachaille/633e164435a2279081178e451476520a

### Panic Output

N/A

### Expected Behavior

I believe VM should build although I have not been able to confirm that Terraform actually supported Oracle Linux 8 builds.

2 disks should be created - 50Gb and 100GB

### Actual Behavior

The above error displays in vSphere in the Task window and the VM Edit Settings window 

Terraform reports

```
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
╷
│ Error: error powering on virtual machine: powerOn task for vm "/{redacted}/{redacted}" failed: Unable to enumerate all disks.
│ 
│   with vsphere_virtual_machine.vm,
│   on oracle_config.tf line 44, in resource "vsphere_virtual_machine" "vm":
│   44: resource "vsphere_virtual_machine" "vm" {
│ 
```

It seems that the 2nd disk is created at some level of the VM configuration because I see Hard Disk 1 and Hard Disk 2 in the vSphere GUI.  The 2nd disk is correctly addressed SCSI(0:1) in the vSphere GUI.  Note my template only has 1 disk, so Terraform is creating this 2nd disk.  

However, the size of the second disk is 0 when it should be 100GB.  Also, the disk file for the 2nd disk is set to the datastore name rather than the expected vmdk file.  

The terraform log reads "2022-03-29T17:11:12.089+0100 [ERROR] vertex "vsphere_virtual_machine.vm" error: error powering on virtual machine: powerOn task for vm "{redacted}" failed: Unable to enumerate all disks."

The following is a selective excerpt from the vmx file created when I set the 2nd disks unit_number to 2

```
[root@{redacted}:/vmfs/volumes/{redacted}/oel-8-test2{redacted}] grep scsi oel-8-test2{redacted}.vmx

scsi0.virtualDev = "pvscsi"
scsi0.present = "TRUE"

scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = "oel-8-test2{redacted}._2.vmdk”.  <—— i.e., A vmdk file
sched.scsi0:0.shares = "normal"
sched.scsi0:0.throughputCap = "off"
scsi0:0.present = "TRUE"

scsi0.pciSlotNumber = "160"
scsi0.sasWWID = "50 05 05 62 11 25 27 80"

scsi1.virtualDev = "pvscsi"
scsi1.present = "TRUE"

scsi2.virtualDev = "pvscsi"
scsi2.present = "TRUE"

scsi0:2.deviceType = "scsi-hardDisk"
scsi0:2.fileName = "/vmfs/volumes/{redacted}”. <—— i.e., the datastore dir
sched.scsi0:2.shares = "normal"
sched.scsi0:2.throughputCap = "off"
scsi0:2.present = "TRUE"

[root@{redacted}:/vmfs/volumes/{redacted}/oel-8-test2{redacted}] grep scsi oel-8-test2{redacted}.vmx
```

### Steps to Reproduce

/var/tmp/terraform init
/var/tmp/terraform plan
/var/tmp/terraform apply (yes)

### Environment Details

I am running Terraform on CentOS 7.

### Screenshots

Descriptions provided instead.

### References

N/A

**Comment by tenthirtyam** [comment] 2022-03-29 17:00
Hi @8uachaille 👋,

Can you please format the console outputs in the **Description** section as code blocks for readability?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by 8uachaille** [comment] 2022-03-29 17:28
> Hi @8uachaille 👋,
> 
> Can you please format the console outputs in the **Description** section as code blocks for readability?
> 
> **Ryan Johnson** Staff II Solutions Architect | VMware, Inc.

Done

**Comment by tenthirtyam** [comment] 2022-03-29 17:36
@8uachaille, Can you confirm that vSphere 6.7 is updated to Update 3 which supports Oracle Linux 8.x?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by 8uachaille** [comment] 2022-03-30 10:04
> @8uachaille, Can you confirm that vSphere 6.7 is updated to Update 3 which supports Oracle Linux 8.x?
> 
> **Ryan Johnson** Staff II Solutions Architect | VMware, Inc.

The VCSA is update 3 - more specifically ...

The vCenter server build is VMware VirtualCenter 6.7.0 build-19299595
This is VCSA | Version | Release Date | VAMI/Release Notes | Client/MOB/vpxd.log
vCenter Appliance 6.7 Update 3q (6.7.0.52000) | 2022-02-08 | 19300125 | 19299595

The vSphere ESXi 6.7 build is 18828794 which is aka ESXi 6.7 P06 and aka ESXi670-202111001
This build was reportedly released 23 Nov 21 whereas U3 was reportedly released 20 Aug 19

The following appears in the created VM's vmx file when I select Oracle 8 Linux in the vsphere GUI so I think it is supported

`   guestOS = "oraclelinux8-64"`

References:

https://kb.vmware.com/s/article/2143838
https://kb.vmware.com/s/article/2143832

**Comment by 8uachaille** [comment] 2022-04-04 14:58
The root disk is enumerated with _2 as part of its filename in the template at install time and this is reflected in the vmx file.  A normal root disk is not enumerated with any suffix like _2 .. instead it would be say fqdn.vmdk not … fqdn_2.vmdk.

I am not sure of why that is but it probably relates to the new requirement for a filesystem for EFI with Oracle Linux [1].  I suspect that is messing up the unit number logic that the disk creation code in the vSphere Terraform provider is based on.

I will build another template and see if that will make it work.  I could mess with the vmdk name / vmk file but I want the template build to be straightforward.

[1] https://docs.oracle.com/en/operating-systems/oracle-linux/8/install/ol8-install-basic.html#install-storage-network :: search "An EFI system partition"

**Comment by 8uachaille** [comment] 2022-04-05 17:17
I have read https://github.com/hashicorp/terraform-provider-vsphere/issues/1578 again and I believe I have the same issue 

I added firmware = efi and efi_secure_boot_enabled = true but these had no positive effect that I can see

```
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
╷
│ Error: error powering on virtual machine: powerOn task for vm "/AT IS Virtual Hosting Datacenter/vm/IS/IS Apps Linux Servers/Oracle-VMs/oel-8-test2.is.ed.ac.uk" failed: Unable to enumerate all disks.
│ 
│   with vsphere_virtual_machine.vm,
│   on oracle_config.tf line 44, in resource "vsphere_virtual_machine" "vm":
│   44: resource "vsphere_virtual_machine" "vm" {
│ 
```

**Comment by 8uachaille** [comment] 2022-04-05 17:44
I tried turning secure boot off in Template and Terraform manifest but the same error resulted

I then reverted back to the following much older versions of Terraform and Provider and those built the VM that I need with  my Terraform manifests adapted as above :)

Terraform v0.12.20
terraform-provider-vsphere_v1.26.0_x4

If possible, I'd like the following new versions of Terraform and Provider to do the build instead :(

Terraform v1.1.7
Terraform Provider v2.1.1

**Comment by usmcguy** [comment] 2022-04-08 19:08
I am closing a duplicate ticket, but I have a similar issue when building Windows VM. Using the older terraform binary and provider mentioned above didnt provide me any different result.

One thing I noticed, I had debug turned on in the provider config. I saw in the SOAP request, even though I had configured a disk size of 100 GB, the request had it set to 0.

**Comment by usmcguy** [comment] 2022-04-20 18:37
Currently this issue prohibits our organization from using Terraform provider with vSphere. Is there a way to escalate this to the v2.2.0 release?

**Comment by aszynkow** [comment] 2022-05-24 02:14
Hi @tenthirtyam,
I am experiencing same issue leading to Tf provider not creating *.vmdk file for a boot volume. 

I am using provider 1.26. 

Please advise on progress for the following: 
https://github.com/hashicorp/terraform-provider-vsphere/issues/1639
https://github.com/hashicorp/terraform-provider-vsphere/issues/1578

Thank you in advance.

**Comment by tenthirtyam** [comment] 2022-05-24 02:59
Apologies, I've been fully occupied by day-to-day priorities and haven't had much time to dedicate to provider contributions such as triage, bug fixes, or new features.

Have you experienced the same issue with the newer releases of the provider? The latest as of this msg is v2.1.1.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by aszynkow** [comment] 2022-05-24 03:32
No worries, @tenthirtyam.

I gave it a go and unfortunately same issue occurred.  

**No vmdk file created.**
[opc@sddc1-2:/vmfs/volumes/vsan:521bc8650d7b5155-bbaf5a89c665a4c5/78508c62-4022-eecd-b1a5-bc97e1c7c600] ls -ltr
total 0
-rwxr-xr-x    1 root     root          1966 May 24 03:26 asz-vm-5.vmx
-rw-r--r--    1 root     root             0 May 24 03:26 asz-vm-5.vmsd
-rw-r--r--    1 root     root           295 May 24 03:26 asz-vm-5-540e5830.hlog
[opc@sddc1-2:/vmfs/volumes/vsan:521bc8650d7b5155-bbaf5a89c665a4c5/78508c62-4022-eecd-b1a5-bc97e1c7c600] 

vmx file points to a vsan folder rather to a specific vmdk file:

scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = **"/vmfs/volumes/vsan:521bc8650d7b5155-bbaf5a89c665a4c5"**
sched.scsi0:0.shares = "normal"
sched.scsi0:0.throughputCap = "off"
scsi0:0.present = "TRUE"

Seem like the DISK part was skipped:

[opc@sddc1-2:/vmfs/volumes/vsan:521bc8650d7b5155-bbaf5a89c665a4c5/78508c62-4022-eecd-b1a5-bc97e1c7c600] cat asz-vm-5-540e5830.hlog
080020ff-ffff-ffff-ffff-0010e0fbbd50
4566272692642273866
success
none
invalid
create
0
Dir F "/vmfs/volumes/vsan:521bc8650d7b5155-bbaf5a89c665a4c5/78508c62-4022-eecd-b1a5-bc97e1c7c600"
Vm F "/vmfs/volumes/vsan:521bc8650d7b5155-bbaf5a89c665a4c5/78508c62-4022-eecd-b1a5-bc97e1c7c600/asz-vm-5.vmx"
[opc@sddc1-2:/vmfs/volumes/vsan:521bc8650d7b5155-bbaf5a89c665a4c5/78508c62-4022-eecd-b1a5-bc97e1c7c600]

Leading to the below:

Error: error powering on virtual machine: powerOn task for vm "/oci-w01dc/vm/asz-vm-5" failed: Unable to enumerate all disks.
│
│   with vsphere_virtual_machine.vm,
│   on main.tf line 51, in resource "vsphere_virtual_machine" "vm":
│   51: resource "vsphere_virtual_machine" "vm" {

Please advise on any possible ETA as this is basically stopping our IaC initiative.

**Comment by tenthirtyam** [comment] 2022-05-24 03:39
I will defer any ETA and/or prioritization to the provider product manager. 

Community contributions are also a welcomed path to help triage and resolve such issues.

cc @tejavar 

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-09-22 04:34
Duplicate of #1578

**Closed by tenthirtyam** 2022-09-22 04:34 UTC
Labels: bug, community/contribution, needs-triage, acknowledged, area/vm, area/storage
