### ISSUE TITLE
Why does vSphere provider require ProfileDrivenStorage?

### ISSUE THREAD

**Issue by FF186** [hashicorp/terraform-provider-vsphere#1404] opened 2021-05-07 07:19 UTC
### Terraform Version
`Terraform v0.14.10`

### vSphere Provider Version
`"1.25.0"`

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Question
Hi, I work in a company where we have a strict "role separation", and the people administrating the vSphere Cluster is not too happy to "give" away permission etc. I therefore have a question regarding the provider and the resource `vsphere_virtual_machine`:

- Why does the vSphere provider require `ProfileDrivenStorage` when creating a virtual machine using the `vsphere_virtual_machine` resource? Packer does not require this.

### Panic Output
`Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: ServerFaultCode: NoPermission: RESOURCE (vm-XXXX), ACTION (queryAssociatedProfile): RESOURCE (vm-XXXX), ACTION (PolicyIDByVirtualDisk)`

### References

* #966

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FF186** [comment] 2021-05-31 10:27
Hi @koikonom,Why is this needed? I know it is essential for provisioning through SPBM.
I'm just trying to see why it is required for Terraform and not Packer even though they are completely different tools.

Thanks.

**Comment by tenthirtyam** [comment] 2021-11-05 03:53
To be clear, you **only** need: Profile-driven Storage > View (`StorageProfile.View`) to be able to read the available storage policies. 

> NOTE: The same is required by vRealize Automation to in order to create storage  profiles so that virtual machines can be deployed to desired datastore(s).

Hope this helps,
Ryan
@tenthirtyam

Recommend: `close/not-a-bug` but could be improved in docs.

**Comment by tenthirtyam** [comment] 2022-01-17 18:52
cc @iBrandyJackson for review and next steps.

**Comment by tenthirtyam** [comment] 2022-01-17 18:53
Also, duplicate of #1216.

**Comment by tenthirtyam** [comment] 2022-01-28 21:44
Hi @FF186, I'm going to close this issue as the context is included in a prior issue, #1216. We'll track this concern in this origination.

Ryan

**Closed by tenthirtyam** 2022-01-28 21:44 UTC
Labels: bug, duplicate
