### ISSUE TITLE
PCI Passthrough devices not attached on first boot

### ISSUE THREAD

**Issue by mike-sol** [hashicorp/terraform-provider-vsphere#1137] opened 2020-07-17 23:56 UTC
### Terraform Version
0.12.26

### vSphere Provider Version
1.21

### Affected Resource(s)
- `vsphere_virtual_machine`

### Expected Behavior

PCI device should have been connected to a new VM at first boot

### Actual Behavior

PCI device was not connected at first boot, though the pci_device_id section in the `terraform apply` output indicated it would be; Terraform completed as though everything was fine. 

Running `terraform apply` again indicated that it needed to change the VM, with the only difference being the PCI passthrough device. Allowing this to proceed worked - it shut down the VM, attached the PCI  device, and booted it back up.

### Steps to Reproduce
Create any VM with PCI passthrough enabled.

### Important Factoids
Running VMware ESXi, 6.7.0, 16075168

### References
https://github.com/hashicorp/terraform-provider-vsphere/pull/1099

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bill-rich** [comment] 2020-07-20 23:35
It sounds like there is a problem with the initial config when setting up a VM with PCI passthrough, but the update portion is working. Can you please provide an example config that will reproduce the issue?

**Comment by mike-sol** [comment] 2020-08-05 20:13
Sorry for the slow response, I was on vacation.

 My config is heavily modularized, but the resulting machine to create looks like this:

```# module.es.vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + boot_delay                              = 10000
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "datastore-38"
      + default_ip_address                      = (known after apply)
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "bios"
      + folder                                  = "Quantum"
      + force_power_off                         = true
      + guest_id                                = "otherLinuxGuest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = "host-41"
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 16384
      + memory_limit                            = -1
      + memory_reservation                      = 16384
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "dws-lab-vm-es"
      + nested_hv_enabled                       = false
      + num_cores_per_socket                    = 1
      + num_cpus                                = 8
      + pci_device_id                           = [
          + "0000:11:00.0",
        ]
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-27"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "lsilogic"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = "aa6d5a82-1c88-45da-85d3-3d74b91a5bad"
      + swap_placement_policy                   = "inherit"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + template_uuid = "42131c74-ce37-5397-2c77-f4d7f722d905"
          + timeout       = 30

          + customize {
              + dns_server_list = [
                  + "172.28.20.3",
                ]
              + dns_suffix_list = [
                  + "lab.dwavesystems.com",
                ]
              + ipv4_gateway    = "172.28.30.1"
              + timeout         = 10

              + linux_options {
                  + domain       = "lab.dwavesystems.com"
                  + host_name    = "dws-lab-vm-es"
                  + hw_clock_utc = true
                }

              + network_interface {
                  + ipv4_address = "172.28.30.12"
                  + ipv4_netmask = 24
                }
            }
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "<computed>"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "disk0"
          + path              = (known after apply)
          + size              = 60
          + storage_policy_id = "aa6d5a82-1c88-45da-85d3-3d74b91a5bad"
          + thin_provisioned  = true
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "e1000"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-91"
        }
    }
```

Let me know if that is enough or if I need to produce a non-modularized version of the config in order to give you the source HCL.

**Comment by mike-sol** [comment] 2020-08-05 20:14
Happy to respin it at any time for you, and can try beta code for the provider (may need some pointers on how to build that, though)

**Comment by mike-sol** [comment] 2020-10-16 21:36
Just a bump for this issue.... let me buy you some beer to help this issue get some priority, maybe? ;)

**Comment by markpeek** [comment] 2020-10-18 23:23
@bill-rich I took a quick look and it appears there needs to be a PciPassthroughPostCloneOperation() implemented and then applied when the clone path is taken when creating a new VM.

**Comment by mike-sol** [comment] 2020-10-19 17:05
Thanks for looking at it @markpeek, beer offer stands for whomever fixes this for me :)

**Comment by mike-sol** [comment] 2020-11-04 22:55
@bill-rich I hate to nag, but having this feature would be absolutely tremendous for me. Please let me know if there's something I can do to help out, if you need more logs, beta testing code, beer, free quantum computing time, you name it.

As mentioned the feature 'works' if Terraform is applied a second time - the provider notices the requested PCI passthrough is not present and stops the VM, attaches the hardware, and starts it again. Problem is that this doesn't happen on first boot, so either a lot of really nasty trickery is needed to detect this and facilitate a clean second run, or I have to catch the process manually in the middle when the VM is first booting and TF is waiting to SSH in to run provisioning for me, stop the VM and add the hardware manually, and boot it up in time for the provisioner to still run. Either way it makes the deployment more painful than it need to be.

Thanks in advance for anything you can do to alleviate that.

**Comment by mike-sol** [comment] 2020-11-04 23:34
I think there's also still some issue with https://github.com/hashicorp/terraform-provider-vsphere/issues/1111 because I've now hit a case where, unlike what I just said, a second apply does not attach the PCI card - it just spits out 

> Error: could not find SystemId

and dies.

**Comment by mike-sol** [comment] 2020-11-11 03:33
My current workaround is to apply with a -target for just the VM, then re-apply so that the resource reconfigures the VM (stopping it, adding PCI card, starting it again) before running my null_resource provisioner. Ugly, but workable. 😐

**Comment by linuxcrash** [comment] 2022-02-21 16:35
I have the exact same issue (vSphere 6.7 U3). 

When cloning to a new VM from a template and then at the same time having a pci_device_id and host_system_id defined, the VM is created and powered on by Terraform but the pci device does not get attached.

I'm using the Terraform vSphere provider version 2.0.2.

Is there any ETA when this gets fixed?

**Comment by tenthirtyam** [comment] 2022-02-21 17:26
Hi @linuxcrash, 👋 

I've added this issue the the Research milestone. When it's prioritized by the maintainers for a release version, it will be updated to an associated release milestone.

If you want to contribute to this project to help research and address the issue, please review the [contributing guidelines](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/docs/CONTRIBUTING.md) and information on [submitting pull requests](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/docs/PULL_REQUESTS.md).

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc. 

Ryan

**Comment by tenthirtyam** [comment] 2022-02-21 17:34
@mike-sol, I'll discuss this with the team one our next chat and see if it can be prioritized for a release soon. It won't make the v2.1.0 payload however.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by linuxcrash** [comment] 2022-02-21 21:26
@tenthirtyam / Ryan,
I don't really want to be the bad guy but I'm a but baffled how this feature made it into a release if in reality its almost non-functional and one can only make it work using workarounds. 

It would be greatly appreciated if a fix for it could be prioritized.

I will have another look tomorrow if there is something I can contribute to make things faster but I fear it needs the proper experts to get it fixed.

Anyways greatly appreciate your effert taking it up with the team.

Regards
Linuxcrash

**Comment by tenthirtyam** [comment] 2022-02-21 22:36
I also took a look at the code this evening and I [agree with @markpeek](https://github.com/hashicorp/terraform-provider-vsphere/issues/1137#issuecomment-711439576). It looks like a `PciPassthroughPostCloneOperation()` needs to be implemented on the sub resource and then added to the `resourceVSphereVirtualMachinePostDeployChanges`.

Ryan

**Comment by linuxcrash** [comment] 2022-02-22 07:45
@tenthirtyam for what I understand this sounds correct. Is there anything I can supply outside of the code changes to help speed up the implementation?

Linuxcrash

**Comment by tenthirtyam** [comment] 2022-02-22 10:50
Hi @linuxcrash,

If you have Terraform support, you can open a case and include your case number.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by linuxcrash** [comment] 2022-02-22 11:03
@tenthirtyam,
Unfortunately we don't but we have VMware support - Could this be a route to use?

Regards

**Comment by tenthirtyam** [comment] 2022-02-22 11:14
Hi @linuxcrash,

At this time, adding a VMware case number would not be beneficial.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-03-17 23:42
@mike-sol - I've implemented a preliminary fix for this issue and my initial testing looks good thus far. The devices are added during the initial clone w/o the need for a re-apply. 

After a few more tests and a little cleanup, I'll submit the pull request. Would you be willing to perform a build on the branch after I file the pull request and test results in your environment?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by linuxcrash** [comment] 2022-03-18 14:25
@tenthirtyam if there is a compiled test build that could be used for testing, I could offer to try and test this on one of our internal lab setups.

Regards

**Comment by tenthirtyam** [comment] 2022-03-18 15:06
> @tenthirtyam if there is a compiled test build that could be used for testing, I could offer to try and test this on one of our internal lab setups.

Are you familiar with how to build the provider and then set to use a local version?

**Comment by linuxcrash** [comment] 2022-03-18 16:39
@tenthirtyam haven't done that so far but if you got a link to the docs I might be able to do something next Monday.

**Comment by tenthirtyam** [comment] 2022-03-18 18:03
So far, so good:

```console
❯ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + annotation                              = (known after apply)
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "datastore-148"
      + default_ip_address                      = (known after apply)
      + efi_secure_boot_enabled                 = false
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "bios"
      + force_power_off                         = true
      + guest_id                                = "ubuntu64Guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = "host-147"
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 4096
      + memory_limit                            = -1
      + memory_reservation                      = 4096
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "ryan-pci-terraform"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 2
      + pci_device_id                           = [
          + "0000:d8:00.1",
        ]
      + power_state                             = (known after apply)
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-100"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + tools_upgrade_policy                    = "manual"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + template_uuid = "420c2d6e-4f7a-c031-bdf9-998a2c4558f0"
          + timeout       = 30

          + customize {
              + timeout = 10

              + linux_options {
                  + domain       = "rainpole.io"
                  + host_name    = "ryan-pci-terraform"
                  + hw_clock_utc = true
                }

              + network_interface {}
            }
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "<computed>"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "disk0"
          + path              = (known after apply)
          + size              = 40
          + storage_policy_id = (known after apply)
          + thin_provisioned  = false
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "dvportgroup-4199"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
vsphere_virtual_machine.vm: Still creating... [30s elapsed]
vsphere_virtual_machine.vm: Still creating... [40s elapsed]
vsphere_virtual_machine.vm: Still creating... [50s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m20s elapsed]
vsphere_virtual_machine.vm: Creation complete after 2m25s [id=420ce5db-853b-fc11-9af4-78f1313c7c54]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

❯ terraform state show vsphere_virtual_machine.vm
# vsphere_virtual_machine.vm:
resource "vsphere_virtual_machine" "vm" {
    boot_delay                              = 0
    boot_retry_delay                        = 10000
    boot_retry_enabled                      = false
    change_version                          = "2022-03-18T17:58:03.682262Z"
    cpu_hot_add_enabled                     = false
    cpu_hot_remove_enabled                  = false
    cpu_limit                               = -1
    cpu_performance_counters_enabled        = false
    cpu_reservation                         = 0
    cpu_share_count                         = 2000
    cpu_share_level                         = "normal"
    datastore_id                            = "datastore-148"
    default_ip_address                      = "10.118.232.85"
    efi_secure_boot_enabled                 = false
    enable_disk_uuid                        = false
    enable_logging                          = false
    ept_rvi_mode                            = "automatic"
    firmware                                = "bios"
    force_power_off                         = true
    guest_id                                = "ubuntu64Guest"
    guest_ip_addresses                      = [
        "10.118.232.85",
        "fe80::250:56ff:fe8c:4dbb",
    ]
    hardware_version                        = 17
    host_system_id                          = "host-147"
    hv_mode                                 = "hvAuto"
    id                                      = "420ce5db-853b-fc11-9af4-78f1313c7c54"
    ide_controller_count                    = 2
    latency_sensitivity                     = "normal"
    memory                                  = 4096
    memory_hot_add_enabled                  = false
    memory_limit                            = -1
    memory_reservation                      = 4096
    memory_share_count                      = 40960
    memory_share_level                      = "normal"
    migrate_wait_timeout                    = 30
    moid                                    = "vm-4215"
    name                                    = "ryan-pci-terraform"
    nested_hv_enabled                       = false
    num_cores_per_socket                    = 1
    num_cpus                                = 2
    pci_device_id                           = [
        "0000:d8:00.1",
    ]
    power_state                             = "on"
    poweron_timeout                         = 300
    reboot_required                         = false
    resource_pool_id                        = "resgroup-100"
    run_tools_scripts_after_power_on        = true
    run_tools_scripts_after_resume          = true
    run_tools_scripts_before_guest_reboot   = false
    run_tools_scripts_before_guest_shutdown = true
    run_tools_scripts_before_guest_standby  = true
    sata_controller_count                   = 0
    scsi_bus_sharing                        = "noSharing"
    scsi_controller_count                   = 1
    scsi_type                               = "pvscsi"
    shutdown_wait_timeout                   = 3
    swap_placement_policy                   = "inherit"
    sync_time_with_host                     = false
    sync_time_with_host_periodically        = false
    tools_upgrade_policy                    = "manual"
    uuid                                    = "420ce5db-853b-fc11-9af4-78f1313c7c54"
    vapp_transport                          = []
    vbs_enabled                             = false
    vmware_tools_status                     = "guestToolsRunning"
    vmx_path                                = "ryan-pci-terraform/ryan-pci-terraform.vmx"
    vvtd_enabled                            = false
    wait_for_guest_ip_timeout               = 0
    wait_for_guest_net_routable             = true
    wait_for_guest_net_timeout              = 5

    clone {
        linked_clone  = false
        template_uuid = "420c2d6e-4f7a-c031-bdf9-998a2c4558f0"
        timeout       = 30

        customize {
            timeout = 10

            linux_options {
                domain       = "rainpole.io"
                host_name    = "ryan-gpu-terraform"
                hw_clock_utc = true
            }

            network_interface {}
        }
    }

    disk {
        attach           = false
        controller_type  = "scsi"
        datastore_id     = "datastore-148"
        device_address   = "scsi:0:0"
        disk_mode        = "persistent"
        disk_sharing     = "sharingNone"
        eagerly_scrub    = false
        io_limit         = -1
        io_reservation   = 0
        io_share_count   = 1000
        io_share_level   = "normal"
        keep_on_remove   = false
        key              = 2000
        label            = "disk0"
        path             = "ryan-gpu-terraform/ryan-gpu-terraform.vmdk"
        size             = 40
        thin_provisioned = false
        unit_number      = 0
        uuid             = "6000C296-6546-84e5-f892-f6fc84a18518"
        write_through    = false
    }

    network_interface {
        adapter_type          = "vmxnet3"
        bandwidth_limit       = -1
        bandwidth_reservation = 0
        bandwidth_share_count = 50
        bandwidth_share_level = "normal"
        device_address        = "pci:0:7"
        key                   = 4000
        mac_address           = "00:50:56:8c:4d:bb"
        network_id            = "dvportgroup-4199"
        use_static_mac        = false
    }
}
```

**Comment by tenthirtyam** [comment] 2022-03-18 18:04
So far so good:

```console
❯ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + annotation                              = (known after apply)
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "datastore-148"
      + default_ip_address                      = (known after apply)
      + efi_secure_boot_enabled                 = false
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "bios"
      + force_power_off                         = true
      + guest_id                                = "ubuntu64Guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = "host-147"
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 4096
      + memory_limit                            = -1
      + memory_reservation                      = 4096
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "ryan-gpu-terraform"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 2
      + pci_device_id                           = [
          + "0000:d8:00.1",
        ]
      + power_state                             = (known after apply)
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-100"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + tools_upgrade_policy                    = "manual"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + template_uuid = "420c2d6e-4f7a-c031-bdf9-998a2c4558f0"
          + timeout       = 30

          + customize {
              + timeout = 10

              + linux_options {
                  + domain       = "rainpole.io"
                  + host_name    = "ryan-gpu-terraform"
                  + hw_clock_utc = true
                }

              + network_interface {}
            }
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "<computed>"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "disk0"
          + path              = (known after apply)
          + size              = 40
          + storage_policy_id = (known after apply)
          + thin_provisioned  = false
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "dvportgroup-4199"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
vsphere_virtual_machine.vm: Still creating... [30s elapsed]
vsphere_virtual_machine.vm: Still creating... [40s elapsed]
vsphere_virtual_machine.vm: Still creating... [50s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m20s elapsed]
vsphere_virtual_machine.vm: Creation complete after 2m25s [id=420ce5db-853b-fc11-9af4-78f1313c7c54]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
❯ terraform state list vsphere_virtual_machine.vm
vsphere_virtual_machine.vm
❯ terraform state show  vsphere_virtual_machine.vm
# vsphere_virtual_machine.vm:
resource "vsphere_virtual_machine" "vm" {
    boot_delay                              = 0
    boot_retry_delay                        = 10000
    boot_retry_enabled                      = false
    change_version                          = "2022-03-18T17:58:03.682262Z"
    cpu_hot_add_enabled                     = false
    cpu_hot_remove_enabled                  = false
    cpu_limit                               = -1
    cpu_performance_counters_enabled        = false
    cpu_reservation                         = 0
    cpu_share_count                         = 2000
    cpu_share_level                         = "normal"
    datastore_id                            = "datastore-148"
    default_ip_address                      = "10.118.232.85"
    efi_secure_boot_enabled                 = false
    enable_disk_uuid                        = false
    enable_logging                          = false
    ept_rvi_mode                            = "automatic"
    firmware                                = "bios"
    force_power_off                         = true
    guest_id                                = "ubuntu64Guest"
    guest_ip_addresses                      = [
        "10.118.232.85",
        "fe80::250:56ff:fe8c:4dbb",
    ]
    hardware_version                        = 17
    host_system_id                          = "host-147"
    hv_mode                                 = "hvAuto"
    id                                      = "420ce5db-853b-fc11-9af4-78f1313c7c54"
    ide_controller_count                    = 2
    latency_sensitivity                     = "normal"
    memory                                  = 4096
    memory_hot_add_enabled                  = false
    memory_limit                            = -1
    memory_reservation                      = 4096
    memory_share_count                      = 40960
    memory_share_level                      = "normal"
    migrate_wait_timeout                    = 30
    moid                                    = "vm-4215"
    name                                    = "ryan-gpu-terraform"
    nested_hv_enabled                       = false
    num_cores_per_socket                    = 1
    num_cpus                                = 2
    pci_device_id                           = [
        "0000:d8:00.1",
    ]
    power_state                             = "on"
    poweron_timeout                         = 300
    reboot_required                         = false
    resource_pool_id                        = "resgroup-100"
    run_tools_scripts_after_power_on        = true
    run_tools_scripts_after_resume          = true
    run_tools_scripts_before_guest_reboot   = false
    run_tools_scripts_before_guest_shutdown = true
    run_tools_scripts_before_guest_standby  = true
    sata_controller_count                   = 0
    scsi_bus_sharing                        = "noSharing"
    scsi_controller_count                   = 1
    scsi_type                               = "pvscsi"
    shutdown_wait_timeout                   = 3
    swap_placement_policy                   = "inherit"
    sync_time_with_host                     = false
    sync_time_with_host_periodically        = false
    tools_upgrade_policy                    = "manual"
    uuid                                    = "420ce5db-853b-fc11-9af4-78f1313c7c54"
    vapp_transport                          = []
    vbs_enabled                             = false
    vmware_tools_status                     = "guestToolsRunning"
    vmx_path                                = "ryan-gpu-terraform/ryan-gpu-terraform.vmx"
    vvtd_enabled                            = false
    wait_for_guest_ip_timeout               = 0
    wait_for_guest_net_routable             = true
    wait_for_guest_net_timeout              = 5

    clone {
        linked_clone  = false
        template_uuid = "420c2d6e-4f7a-c031-bdf9-998a2c4558f0"
        timeout       = 30

        customize {
            timeout = 10

            linux_options {
                domain       = "rainpole.io"
                host_name    = "ryan-gpu-terraform"
                hw_clock_utc = true
            }

            network_interface {}
        }
    }

    disk {
        attach           = false
        controller_type  = "scsi"
        datastore_id     = "datastore-148"
        device_address   = "scsi:0:0"
        disk_mode        = "persistent"
        disk_sharing     = "sharingNone"
        eagerly_scrub    = false
        io_limit         = -1
        io_reservation   = 0
        io_share_count   = 1000
        io_share_level   = "normal"
        keep_on_remove   = false
        key              = 2000
        label            = "disk0"
        path             = "ryan-pci-terraform/ryan-pci-terraform.vmdk"
        size             = 40
        thin_provisioned = false
        unit_number      = 0
        uuid             = "6000C296-6546-84e5-f892-f6fc84a18518"
        write_through    = false
    }

    network_interface {
        adapter_type          = "vmxnet3"
        bandwidth_limit       = -1
        bandwidth_reservation = 0
        bandwidth_share_count = 50
        bandwidth_share_level = "normal"
        device_address        = "pci:0:7"
        key                   = 4000
        mac_address           = "00:50:56:8c:4d:bb"
        network_id            = "dvportgroup-4199"
        use_static_mac        = false
    }
}
```

**Comment by tenthirtyam** [comment] 2022-03-18 18:19
@mike-sol @linuxcrash - You can download the [bug/gh-1137](https://github.com/hashicorp/terraform-provider-vsphere/tree/bug/gh-1137) branch and build the provider for the architecture of the system you are on. You will need Go 1.16 or higher.

``` console
cd terraform-provider-vsphere-bug-gh-1137
go get
go build
```

Then use the [Manual Installation](https://github.com/hashicorp/terraform-provider-vsphere/blob/bug/gh-1137/docs/INSTALL.md#manual-installation) method to save a local version for use and then use a version of `v2.2.0` for example.

macOS Example:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/7771363/159060743-7e1455a3-0497-414c-88d8-d85c249a240c.png">

In your `terraform{}` block, use something like the following for the `required_versions` to pick up the local version.

```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "local/hashicorp/vsphere"
      version = "2.2.0"
    }
  }
  required_version = ">= 1.1.7"
}
```

This will ensure that it pulls the version you named as 2.2.0 from the local plugins path during a fresh `terraform init`.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by linuxcrash** [comment] 2022-03-21 17:59
@tenthirtyam
I tested as suggested above and my VM was created with the PCI Device attached and also powered on successfully. Looks good!

Regards
Linuxcrash

**Comment by tenthirtyam** [comment] 2022-03-21 18:06
That's wonderful news, @linuxcrash.

cc @appilon re: PR 1625.

**Comment by appilon** [comment] 2022-04-04 20:11
I am taking a look at this issue and associated PR now, any chance someone can link a simplified config for reproduction? I would love to get a test case added.

**Comment by tenthirtyam** [comment] 2022-04-04 20:24
Hey Alex,

If the testbed has available physical PCI device to passthrough through to VMs you can use the folowing:

```hcl
data "vsphere_host" "host1" {
  name          = "esxi-01.example.com"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
# ... other configuration...
host_system_id = data.vsphere_host.host1.id
pci_device_id  = [
        "0000:d8:00.1",
    ]
# ... other configuration ...
}

or

```hcl
data "vsphere_host" "host1" {
  name          = "esxi-01.example.com"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_host_pci_device" "host1-gpu1" {
  host_id = data.vsphere_host.host1.id
  name_regex = "foo"
}

resource "vsphere_virtual_machine" "vm" {
# ... other configuration...
host_system_id = data.vsphere_host.host1.id
pci_device_id  = [
        "data.vsphere_host_pci_device.host1-pci.id",
    ]
# ... other configuration ...
}

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by appilon** [comment] 2022-04-06 16:40
My goal is to write an acceptance test for the open PR #1625 ... unfortunately I don't have a physical setup I test on equinix metal. I will have to just manually review that PR..

**Closed** 2022-04-06 19:29 UTC
Labels: bug, confirmed, area/vm

**Comment by tenthirtyam** [comment] 2022-04-06 19:33
> Thanks for looking at it @markpeek, beer offer stands for whomever fixes this for me :)

I'll take an "Arnold Palmer". 🙃

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
