### ISSUE TITLE
Increasing `memory` to over 3072MB with `hot_plug_memery` on Linux 64-bit fails

### ISSUE THREAD

**Issue by ninjaslothx** [hashicorp/terraform-provider-vsphere#1352] opened 2021-03-01 03:19 UTC
### Terraform Version

0.14.7

### vSphere Provider Version

1.24.3 

### Affected Resource(s)

- `vsphere_virtual_machine`

### Expected Behavior

When reconfiguring a linux 64 bit virtual machine to over 3072MB of memory with hot-plug enabled, the virtual machine needs to be shutdown for the configuration to be applied successfully. 

### Actual Behavior

The resource is not shutdown and reconfiguration errors with `Invalid virtual machine configuration`

### Steps to Reproduce

1. create a linux 64 bit virtual machine resource with 1vCPU, 2G of memory. 
2. ensure `memory_hot_add_enabled` is true.
3. terraform apply / create the virtual machine. 
4. edit virtual machine resource to 4G of memory.
5. terraform apply / update virtual machine. 

### References

KB article with the hot plug limitation. 
https://kb.vmware.com/s/article/2008405

### Additional Notes

The terraform run will actually succeed, but the resource increase will not take place (due to the error on the vsphere/vcenter side). This will cause terraform to attempt to repeat the operation on ever subsequent apply 

We might need a simple before/after memory calculation to see if `d.Set("reboot_required", true)` should be set for the run.
I'm unsure the behaviour of operating systems outside of that KB article however. It might require additional validation based on the OS so there is no needless shutdowns.

**Comment by tenthirtyam** [comment] 2022-02-03 18:31
I can confirm that this issue does exist and is a limitation of hot-add in vSphere. It would need additional validations based on the specific guest operating system version and the architecture in which this impacts. 

I'm more inclined to recommend that this is an enhancement vs a bug since it is a vSphere limitation. This could be, at a minimum, addressed in the docs for `vsphere_virtual_machine` resource since there are higher voted enhancements.

Change to `enhancement` from `bug`. Adding `documentation`, too.

cc @appilon for adding thoughts.

Ryan

**Closed** 2022-02-07 22:17 UTC
Labels: enhancement, documentation, acknowledged
