### ISSUE TITLE
ESXi error - Configured PCI devices are not attached to the VM.

### ISSUE THREAD

**Issue by noyrosen** [hashicorp/terraform-provider-vsphere#1467] opened 2021-08-17 09:38 UTC
### Terraform Version
...
```
Terraform v1.0.4
on linux_amd64
```
### vSphere Provider Version
v7.0.2
### Affected Resource(s)
resource "vsphere_virtual_machine" "vm_udu" {
    
    name                       = "cyrus2nr-udu1"
    resource_pool_id           = data.vsphere_resource_pool.pool.id
    datastore_id               = data.vsphere_datastore.datastore.id
    host_system_id             = data.vsphere_host.host.id
    num_cpus = var.num_cpus_udu1
    num_cores_per_socket = var.num_cpus_udu1
    cpu_reservation = var.host_cpu_freq == "" ? (var.auto_host_cpu_freq * var.num_cpus_udu1) : (var.host_cpu_freq * 
    var.num_cpus_udu1)
    cpu_share_level = "high"

    memory   = var.memory_udu1
    memory_reservation = var.memory_udu1
    memory_share_level = "high"

    guest_id = data.vsphere_virtual_machine.template_udu.guest_id
    pci_device_id = ["0000:5e:0e.0","0000:5e:0e.1","0000:5e:0a.0"]

    scsi_type = data.vsphere_virtual_machine.template_udu.scsi_type

    network_interface {
        network_id   = data.vsphere_network.network_udu_1.id
        adapter_type = data.vsphere_virtual_machine.template_udu.network_interface_types[0]
    }

    disk {
        label            = "disk0.vmdk"
        size             = data.vsphere_virtual_machine.template_udu.disks.0.size
        eagerly_scrub    = data.vsphere_virtual_machine.template_udu.disks.0.eagerly_scrub
        thin_provisioned = data.vsphere_virtual_machine.template_udu.disks.0.thin_provisioned
        io_limit         = 1000
    }
    disk {
        label       = "disk1"
        size        = "48"
        unit_number = 1
        thin_provisioned = false
        io_limit    = 1000
    }

    clone {
        template_uuid = data.vsphere_virtual_machine.template_udu.id
    }

    cdrom {
        client_device = true
    }

    // Attach the cloudcongif as a OVF property "user-data"
    vapp {
        properties = {
            "user-data" = base64encode(local_file.cloudconfig-udu.content)
        }
     }
}
### Terraform Configuration Files
Attached above.
### Debug Output
N/A
### Panic Output
![image](https://user-images.githubusercontent.com/89026642/129702004-62dc6da3-9450-49b0-8032-24033eba3c5e.png)
![image](https://user-images.githubusercontent.com/89026642/129702031-6326b7b7-a7ab-470a-8f5c-b46a37ce23ea.png)
### Expected Behavior
VM should start with 3 PCI - VF devices supplied.
### Actual Behavior
None of the PCI devices attached to the VM.
Screenshots attached.
### Steps to Reproduce
1. Define some PCI devices on ESXi host (direct-path passthrough devices)
2. Create a tf file with VM resource and pci_device_id parameter filled with a number of pci addresses, e.g.
resource "vsphere_virtual_machine" "vm" { ... pci_device_id = ["0000:b5:00.0","0000:b5:00.1"] ...}
as described above.

### Important Factoids
None.
### References
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment] 2022-02-04 01:18
Duplicate of #1285.

**Closed** 2022-02-04 01:18 UTC
Labels: bug, duplicate
