### ISSUE TITLE
Creating a virtual_machine requires VirtualMachine.Config.SwapPlacement privilege

### ISSUE THREAD

**Issue by nagstaku** [hashicorp/terraform-provider-vsphere#1790] opened 2022-11-19 19:01 UTC
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.3.5

### Terraform Provider

v2.2.0

### VMware vSphere

VMware vCenter Server 7.0.3 build-19717403

### Description

Facing the same problem as https://github.com/hashicorp/terraform-provider-vsphere/issues/1212

### Affected Resources or Data Sources

resource/vsphere_virtual_machine

### Terraform Configuration

[https://gist.github.com/nagstaku/d3454c4faa316a1572a747907bcf1d0e](url)

### Debug Output

[https://gist.github.com/nagstaku/fe08fe86c7f3b0d60ef88bb73bc31ad4](url)

### Expected Behavior

A VM is created

### Actual Behavior

Error

### Steps to Reproduce

tf apply

### References

#1212

**Comment by tenthirtyam** [comment] 2022-11-19 20:35
Duplicate of #1212

**Comment by tenthirtyam** [comment] 2022-11-19 21:27
This privilege requirement is mentioned in the provider documentation.

Reference: https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs#notes-on-required-privileges

**Closed** 2022-11-19 21:39 UTC
Labels: documentation

**Comment by nagstaku** [comment] 2022-11-19 21:41
Ahh, I thought the setting of it was dropped in 2.2.0 thus avoiding an unnecessary permissions check failure.

**Comment by tenthirtyam** [comment] 2022-11-19 23:14
The privilege is required by the provider’s implementation. PR #1672 updated the documentation.
